core/src/main/scala/scalaz/Map.scala
The documentation of the `f` parameter in `==>>.insertWith` and `==>>.insertWithKey` has mixed up the `existingValue` and `insertedValue` parameters:
```scala
scala> ==>>.singleton(0, 10).insertWith((existing, inserted) => inserted + 1, 0, 20)
res8: scalaz.==>>[Int,Int] = Bin(0,11,Tip,Tip)
scala> ==>>.singleton(0, 10).insertWith((existing, inserted) => existing + 1, 0, 20)
res9: scalaz.==>>[Int,Int] = Bin(0,21,Tip,Tip)
```
The first is actually the `insertedValue` and the second is actually the `existingValue`. This PR swaps the parameter names in the docstring.
=> Fix documentation of ==>>.insertWith{,Key}

core/src/main/scala/scalaz/std/Set.scala, tests/src/test/scala/scalaz/std/SetTest.scala
Open up <code>scalaz/std/Set.scala</code>. Change the definition of <code>foldRight</code> in <code>SetInstances</code> to:
```scala
def foldRight[A, B](fa: Set[A], z: => B)(f: (A, => B) => B) = {
import scala.collection.mutable.ArrayStack
val s = new ArrayStack[A]
fa.foreach(a => s += a)
var r = z
while (!s.isEmpty) {
val w = r // <-- add this
r = f(s.pop, w)
}
r
}
```
```scala
scala> Set(0).foldLeftM[Option, Int](0) { case (x, y) => Some(x+y) } 
res0: Option[Int] = Some(0)
```
Signed-off-by: Mark <m4farrel@uwaterloo.ca>
=> Fixed foldLeftM stack overflows on Set #866

tests/src/test/scala/scalaz/concurrent/ActorTest.scala
I believe there is a race condition between actor2 and actor1 when the ping pong happens. The countdown should happen before you ping a message to the actor otherwise, you can potentially encounter a hang.
PS: This is my first 1) contribution to an OSS project ever, 2) first pull request ever. so please ignore my mistakes if any.
=> Fixed a minor race between the two actors in the message loss test

concurrent/src/main/scala/scalaz/concurrent/Future.scala
A generic param A was being forced into a String => Trampoline[Unit].
This shouldn't be encountered under normal use, and I found it when using ```Task.async``` incorrectly. Nevertheless, it is always nice to remove a cast.
=> Fix a cast exception

project/build.scala
Current URL link (http://opensource.org/licenses/bsd-license.php) move "The BSD 2-Clause License" page.
=> fix license url for pomExtra

core/src/main/scala/scalaz/Free.scala
Part of what makes Free slow is the expansion of Gosubs in the resume method.  This change drastically reduces the number of necessary resume calls made(which happens when folding a Free structure or calling go on a trampoline) and results in about a 8-10% performance improvement when testing with both trampolines and generic free structures.
https://github.com/vmarquez/scalaz/blob/free_jmhtesting/bench/src/main/scala/scalaz/FreeBench.scala 
Is a branch with jmh testing if anyone wants to replicate/tune.  (thanks to @julien-truffaut for the jmh templates) I've also created additional tests with caliper and found (on average) identical results.  After testing various numbers, 500 appeared to be the drop off point for any measurable improvement, though even much smaller sizes did result in …
=> Performance improvement for Free/Trampoline (~10%)

project/build.scala
`-Yno-generic-signatures` is unnecessary for scala 2.11+ and breaks Java based reflection. Apply `-Yno-generic-signatures` only to versions of scala that need it.
=> no generic signatures for scala 2.10.x, see SI-7932, #571 and #828

core/src/main/scala/scalaz/FreeAp.scala
Noticed some style inconsistencies:
- use `ap(x.v(),x.k())` instead of  `ap(x.v() -> x.k())` (tuple syntax instead of `->`)
- in `monadic` replace the two type lambdas with the nicer kind-projector version
=> Some consistency changes in FreeAp

scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala
This was overlooked when StateT was changed to no longer require a type
parameter with a covariant parameter.
=> Remove unneccessary covariance requirement

scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalaCheckBinding.scala
Gen.value was deprecated in Oct 2013 and deleted in May 2014;  newer versions of scalacheck can slip into the build due to transitive dependencies, even if users choose the older version that 7.1.2 passes under.
Assuming this change doesn't break the build, I hope you will release this as 7.1.3, soonish.
=> fix binary incompatibility with recent scalacheck

core/src/main/scala/scalaz/EitherT.scala, tests/src/test/scala/scalaz/EitherTTest.scala
First PR, hope I've followed the correct conventions. Apologies if this is duplicating existing functionality; if so I wasn't able to find it.
Add an `EitherT` factory method that infers the outer type constructor. This makes it easier to use `EitherT` with monad types that have multiple parameters e.g. `State` - currently one has to use explicit type parameters (including a type lambda) when calling `EitherT.eitherT` (or `new EitherT`) with a `State`.
The use of `Functor` in the first `Unapply` is somewhat arbitrary/pragmatic, with the rationale that it's a very weak type and an `EitherT` for an `F[_]` that doesn't even have a `Functor` instance is somewhat useless. Very open to any better alternative here, or a way to avoid needing to specify a typeclass at all.
The `Unapply2` is unused …
=> Add EitherT factory method that infers the outer type constructor

core/src/main/scala/scalaz/Unapply.scala, core/src/main/scala/scalaz/syntax/BitraverseSyntax.scala, tests/src/test/scala/scalaz/UnapplyTest.scala
This uses a trick for approximating the effect of multiple parameter lists (a trick I learned [from Miles](https://gist.github.com/milessabin/cadd73b7756fe4097ca0), of course) to provide `UnapplyProduct` instances. This means that the following finally works:
```scala
import scalaz._, Scalaz._
(1, 'a).bitraverseU(_.set("saw int" :: Nil), _.set("saw sym" :: Nil))
```
I've added a compilation test on the model of the other `Unapply` types, but no tests for syntax.
=> Add working UnapplyProduct

core/src/main/scala/scalaz/syntax/BitraverseSyntax.scala
Since @travisbrown  fixed `bitraverseU` in https://github.com/scalaz/scalaz/pull/969 , it's useful to have the sequence version using the type inference provided by UnapplyProduct.
=> add bisequenceU that uses the now fixed bitraverseU

core/src/main/scala/scalaz/EphemeralStream.scala, core/src/main/scala/scalaz/Foldable.scala, core/src/main/scala/scalaz/syntax/FoldableSyntax.scala, tests/src/test/scala/scalaz/FoldableTest.scala
We found that this method was useful in our code base when trying to find out an element matching a given criterion after being mapped to another value. We originally provided it on `List` but I thought that this could be useful for any `Foldable` given an interim transformation to an `EphemeralStream`.
=> Added a findMapM method for Foldables

core/src/main/scala/scalaz/Monoid.scala, core/src/main/scala/scalaz/Semigroup.scala
and used it in default implementation of Monoid[F].multiply.
Straight port of times1p from the haskell semigroups package.
=> Added multiply1 on Semigroup with efficient default implementation

core/src/main/scala/scalaz/Tree.scala
Fixes issue 673, `Tree.drawTree` stack overflow for wide trees. After trampolining `drawTree`, it started to throw `OutOfMemoryError` on large trees. I rewrote it to use `Vector[StringBuilder]` to represent the lines of the tree representation instead of `Stream[String]`, and had to represent the lines backwards for efficient prepending. Now, it works for trees up to 6000 members before it runs out of memory on my laptop. I have a local test, but it's a bit slow.
=> Fixed drawTree stack overflow and memory usage problems

core/src/main/scala/scalaz/LazyOptionT.scala, core/src/main/scala/scalaz/MaybeT.scala, core/src/main/scala/scalaz/OptionT.scala
`getOrElse` but with `Monoid.zero` as the default value
=> Add `orZero` and `~` to `OptionT`, `LazyOptionT`, and `MaybeT`

core/src/main/scala/scalaz/Tag.scala, example/src/main/scala/scalaz/example/TagUsage.scala, tests/src/test/scala/scalaz/TagTest.scala
This would help me scrap some boilerplate.  Any objections?
=> enable pattern matching on `TagOf` instances

core/src/main/scala/scalaz/Leibniz.scala, project/build.scala
Kind Projector version > 0.6.0 supports simple type bounds.
I used Intellij IDEA 15 inspection to find cases where kind projector can be used instead of regular type projections for type lambdas.
=> Use kind projector for type lambdas with type bounds

core/src/main/scala/scalaz/std/Option.scala, core/src/main/scala/scalaz/syntax/std/OptionOps.scala, tests/src/test/scala/scalaz/OptionalTest.scala
Convenience functions to transform an Option[A] to a ValidationNel[E,A]
or an Option[A] to a ValidationNel[A,B]
=> Add failureNel, successNel to Option

core/src/main/scala/scalaz/package.scala
Trying to improve discoverability a little in the API docs.
=> Add doc links between Lens/PLens types/aliases

example/src/main/scala/scalaz/example/AdjunctUsage.scala
Tiny typo, not sure if such commits are welcome, but aspiring to contribute.
=> Fix a typo in AdjunctUsage example.

core/src/main/scala/scalaz/syntax/BindSyntax.scala
I often use this to do something in monad context without sensible output value. e.g. with State or IO.
=> new combinator in BindSyntax. bind with ignored result of function

example/src/main/scala/scalaz/example/AdjunctUsage.scala, example/src/main/scala/scalaz/example/MixedBag.scala, example/src/main/scala/scalaz/example/STUsage.scala, example/src/main/scala/scalaz/example/UnapplyInference.scala, example/src/main/scala/scalaz/example/WordCount.scala
In the examples, I found some type lambdas that are not yet written using kind-projector sugar, so I replaced them with the nicer sugar variant.
=> examples: Use kind-projector lambdas

core/src/main/scala/scalaz/BindRec.scala
Instead of having its own `foreverRec` method.
Pointed out by @tonymorris.
=> BindRec should override `forever`

core/src/main/scala/scalaz/Cofree.scala, tests/src/test/scala/scalaz/CofreeTest.scala, tests/src/test/scala/scalaz/Eq1.scala
I was wrong.
`scalaz.NaturalTransformation` is not typeclass.
- https://github.com/scalaz/scalaz/commit/a05ab2c0053d54b37474e48fcc1056
- https://github.com/scalaz/scalaz/commit/286c3398adebf0a6759cf498f167f7
=> delete cofreeEqual and cofreeZipEqual

core/src/main/scala/scalaz/std/Tuple.scala, tests/src/test/scala/scalaz/std/TupleTest.scala
Due to the hierarchy, given Semigroup[A], this also gives rise to:
1. Apply[Tuple2[A, ?]]
2. Bind[Tuple2[A, ?]]
=> Add Semigroup[A] => BindRec[Tuple2[A, ?]]

core/src/main/scala/scalaz/ReaderWriterStateT.scala, tests/src/test/scala/scalaz/ReaderWriterStateTTest.scala
This is the same change as 
https://github.com/scalaz/scalaz/pull/949
in that it allows for stack safety as long as any underlying F is trampolined or otherwise a free monad.  This touches a lot less than IndexedStateT and so hopefully a lot easier to review.
=> Refactor RWST to allow for trampolining

core/src/main/scala/scalaz/StreamT.scala, tests/src/test/scala/scalaz/StreamTTest.scala
This is just adding Foldable instance for StreamT.
I would like to remove `StreamT#foldLeft` and `StreamT#foldRight` for 2 reasons.
1. These method have lazy signatures, but works strict.
2. These should be done by `StreamT#toStream.map(_.foldLeft)` or `StreamT#toStream.map(_.foldRight)`.
I have not done anything with `foldLeft` or `foldRight` yet.
Could we do anything with these (like add `@deprecated`)?
Thanks.
=> Add Foldable[StreamT] instance

core/src/main/scala/scalaz/Apply.scala, core/src/main/scala/scalaz/Bind.scala, core/src/main/scala/scalaz/syntax/ApplySyntax.scala
* Added `*>` and `<*` to the instance, instead of just in the syntax.
* Added forever to syntax also.
Example usage:
```scala
import scalaz._, Scalaz._, effect._, IO._
val a: IO[Unit] = putStrLn("Hello, world!")
val b: IO[Unit] = a.forever
b.unsafePerformIO // prints "Hello, world!" forever
```
=> Generalize forever to Apply

core/src/main/scala/scalaz/Bifunctor.scala, core/src/main/scala/scalaz/syntax/BifunctorSyntax.scala, example/src/main/scala/scalaz/example/BifunctorUsage.scala
Adds a function `widen` to take advantage of the natural covariance of `Bifunctor`. I was initially going to implement this for `EitherT` because that was my use-case, but this is probably more useful.
=> Add Bifunctor widen

core/src/main/scala/scalaz/Free.scala
While investigating some performance regressions in one of our web services, I noticed that between scalaz 7.0.x and 7.1.x there was a performance degradation in `Free`. We use `IO` and `Free` heavily throughout our code so these had a noticeable impact.
While looking at the changes to `Free` in 7.2, I found this series of commits from @vmarquez. Hopeful, I back ported them to the series/7.1.x branch and did some testing. In my testing, I saw similar performance gains to what @vmarquez reported, yielding significant improvements in the response time and throughput of our service.
There were other significant changes to `Free` in 7.2 so that these changes ended up not being incorporated in that release. But those changes are not backwards compatible and these changes offer a quick …
=> Backport performance improvements to Free in series/7.1.x

core/src/main/scala/scalaz/IList.scala
This is a trivial alpha-renaming.
The method must have been named `inits0` by accident.
=> Rename the tailrec function inside IList#tails to tails0.

core/src/main/scala/scalaz/Memo.scala
Just importing `collection.mutable` and `collection.immutable` makes the code much more readable ;^)
=> Uses more readable references to mutable and immutable collections

core/src/main/scala/scalaz/NonEmptyList.scala, tests/src/test/scala/scalaz/NonEmptyListTest.scala
The original implementation was converted to a test of correctness.
=> Make NonEmptyList#tails stack safe.

core/src/main/scala/scalaz/Foldable.scala, core/src/main/scala/scalaz/syntax/FoldableSyntax.scala
Counts how many matches of a predicate occur in a Foldable.
The same as:
filterLength f = length . filter f
But this version is manually fused, for better efficiency in Scala.
=> Add a `filterLength` function

core/src/main/scala/scalaz/NonEmptyList.scala
`IList` has both `tails` and `inits`, so I think `NonEmptyList` should, too.
The implementation is in terms of `tails` and `reverse`, which is analogous to the implementation of `IList#inits`.
=> Add method NonEmptyList#inits.

core/src/main/scala/scalaz/Free.scala, core/src/main/scala/scalaz/FreeT.scala, tests/src/test/scala/scalaz/FreeTTest.scala
This concludes a series (#1115, #1116) of refactorings eliminating the need for `Functor[S]` instance for all operations except `resume`/`runM` and all typeclass instances except `Foldable`/`Traverse`.
=> Don't require Functor[S] for MonadPlus[FreeT[S, M, ?]] and MonadError[FreeT[S, M, ?], E]

core/src/main/scala/scalaz/FreeT.scala, tests/src/test/scala/scalaz/FreeTTest.scala
It is crucial that
Gosub(a, f1) >>= f2
is not transformed _eagerly_ to
Gosub(a, x => f1(x) >>= f2)
because then
Gosub(a, f1) >>= f2 >>= f3 >>= f4 >>= ...
builds up `Gosub(a, g)` with `g` stack-unsafe.
On the other hand, if we keep it as
Gosub(...Gosub(Gosub(Gosub(Gosub(a, f1), f2), f3), f4)...)
we then in `resume` compose functions from the right and each of the composed functions is stack safe (`f3`, `f4` are composed to `g3 = x => Gosub(f3(x), f4)`, then `f2`, `g3` to `g2 = x => Gosub(f2(x), g3)` and finally `f1`, `g2` to `g1 = x => Gosub(f1(x), g2)`. We see that stack-safety of each _g<sub>i</sub>_ depends only _f<sub>i</sub>_, not on _g<sub>i+1</sub>_, so the stack frames don't add up.)
As a consequence, for `FreeT[S, M, ?]` to be a `Functor`, `M` must be at least `Applicative`.
I …
=> More stack-safety for FreeT.

core/src/main/scala/scalaz/Free.scala, core/src/main/scala/scalaz/FreeT.scala, tests/src/test/scala/scalaz/FreeTTest.scala
This is a follow up to #1113 and #1115.
Changing `FreeT[S, M, A]` encoding slightly and embracing that `M` will eventually need to be a monad anyway, so it is OK to require `Applicative[M]` anywhere, we are able to lift more `S[_]: Functor` constraints on `FreeT` operations.
The encoding and constraints on `S` are now more analogous to `Free`.
=> Relax more FreeT constraints

core/src/main/scala/scalaz/ISet.scala, tests/src/test/scala/scalaz/ISetTest.scala
Our ISet is based on v0.5.0.0. We can introduce new functions.
ref.
https://github.com/haskell/containers/compare/v0.5.0.0...v0.5.7.1?diff=split&name=v0.5.7.1#diff-13
https://github.com/haskell/containers/compare/v0.5.0.0...v0.5.7.1?diff=split&name=v0.5.7.1#diff-a9b15bd3edd743a14b46e25762f4fe8cR1122
https://github.com/haskell/containers/compare/v0.5.0.0...v0.5.7.1?diff=split&name=v0.5.7.1#diff-a9b15bd3edd743a14b46e25762f4fe8cR1481
=> Update ISet based on Haskell v0.5.7.1 updates

core/src/main/scala/scalaz/syntax/IdOps.scala
Deprecates `unsafeTap` in 7.2.x, which has been removed in 7.3.x via 8fd1b3b. See discussion in #1128.
=> deprecate unsafetap

core/src/main/scala/scalaz/StreamT.scala, tests/src/test/scala/scalaz/StreamTTest.scala
`StreamT[M, A]#toStream` requires evaluation of the whole stream, either eagerly, or later (depending on the monad `M`). As a consequence, it cannot be used on an infinite `StreamT`.
This PR adds a method `asStream`, which works only if `M =:= Id`, but the resulting `Stream` is lazy.
=> Add StreamT#asStream: conversion of StreamT[Id, A] to a lazy Stream[A].

core/src/main/scala/scalaz/StreamT.scala, tests/src/test/scala/scalaz/StreamTTest.scala
`StreamT[M, A]` operations can be written in a stack-safe fashion when `M` is a tail-recursive monad (i.e. when `M[_]: BindRec`), without the need for trampolining the stream. This PR adds these stack-safe versions.
~~With each test I also added a negative test for the original operation that stack-overflows.~~ I deleted those negative tests, because I was not able to test for stack overflow in a platform-independent manner (`StackOverflowError` on JVM vs. `RangeError` in JS).
=> Add stack-safe versions of StreamT[M, A] operations

concurrent/src/main/scala/scalaz/concurrent/Future.scala
I was trying out the Task#retry functionality in Task and I found that it uses a scalaz.concurrent.Timer to implement its logic, and it appears scalaz.concurrent.Timer uses Thread.sleep.
Following the example of Future#timed, which uses the ScheduledExecutorService, we can avoid the use of Thread.sleep in the implementation of Task#retry
=> Change after function to use scheduler instead of Timer

core/src/main/scala/scalaz/EphemeralStream.scala
Prior to this, running the code below resulted in a runtime exception saying that the head of an empty stream was being accessed
```
val es = EphemeralStream.unfold(0)(n => if (n < 5000) Some((List.fill(10000)(500L), n+1)) else None)
es.foldLeft( ().point[IO])(io => e => io >> IO.putStrLn(e.length.shows)).unsafePerformIO
```
Note, the above still doesn't work properly. It results in an OOME, as does 
```
es.traverse_(e => IO.putStrLn(e.length.shows))
```
which is what I'm really trying to get working properly. 
Also of note is that
```
es.foldLeft( ().point[IO])(io => e => io *> IO.putStrLn(e.length.shows)).unsafePerformIO
```
DOES work. But, if you inline `*>`
```
es.foldLeft( ().point[IO])(io => e => Apply[IO].apply2(io, IO.putStrLn(e.length.shows))((_, _) => ())).unsafePerformIO
```
it …
=> change EphemeralStream.foldLeft to use a tail recursive loop

concurrent/src/main/scala/scalaz/concurrent/Strategy.scala
Related to https://github.com/scalaz/scalaz/issues/1105, here's a PR for making the default executor thread pool size at least 4, to avoid nasty deadlocks on 1-core machines.
=> Default executor uses at least 4 threads

scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazProperties.scala
Sadly we are still stuck on 7.1, but other parts of our stack have forced us to use scalacheck 1.12.x. This results in a runtime error when running the traverse laws. 
Can we please apply this band aid to get a scalacheck-binding 7.1.9 that doesn't use the deprecated at 1.11.x and removed in 1.12.x Arbitrary.resize function? 
It would help us out greatly, and I see the last scalaz 7.1.8 was fixing something very similar, so I figured that further fixes in that regard would be helpful. :)
=> Fixes binary incompatibility with scalacheck 1.12.x

core/src/main/scala/scalaz/FreeT.scala, tests/src/test/scala/scalaz/FreeTTest.scala
This method is analogous to `Free#foldMapRec`.
As opposed to `FreeT#runM`, it doesn't require `Functor[S]`.
=> Add FreeT#foldMap.

core/src/main/scala/scalaz/std/String.scala, core/src/main/scala/scalaz/syntax/std/StringOps.scala
We need these two types in quasar (see https://github.com/quasar-analytics/quasar/pull/1193).
Also switched them to not use try/catch directly, but could take or leave that change.
Resubmitted against series/7.3.x. See #1166.
=> Add parseBigInt and parseBigDecimal to std.String

core/src/main/scala/scalaz/Foldable.scala, core/src/main/scala/scalaz/syntax/FoldableSyntax.scala
```splitBy``` splits the elements into groups that produce the same result  by a function f:
```scala
scala> List("A","B","C", "AA","AB", "A", "ABC", "EFG") splitBy (_.length)
res1: scalaz.IList[(Int, scalaz.NonEmptyList[String])] =
[(1,NonEmpty[A,B,C]),(2,NonEmpty[AA,AB]),(1,NonEmpty[A]),(3,NonEmpty[ABC,EFG])]
```
following @ritschwumm comment, also added ```splitByRelation``` that splits into groups of elements that are transitively dependant by a relation r:
```scala
scala> List("A","BA","BC", "AA","BC", "AC") splitByRelation ((s1, s2) => !s2.intersect(s1).isEmpty)
res6: scalaz.IList[scalaz.NonEmptyList[String]] = [NonEmpty[A,BA,BC],NonEmpty[AA],NonEmpty[BC,AC]]
```
=> Foldable.splitBy and splitByRelation

core/src/main/scala/scalaz/EphemeralStream.scala, core/src/main/scala/scalaz/std/Stream.scala, tests/src/test/scala/scalaz/EphemeralStreamTest.scala, tests/src/test/scala/scalaz/std/StreamTest.scala
Lifting a `Semigroup` into `Option` to get a `Monoid` unfortunately makes an always-strict `mappend`, meaning a strict fold.  Here we avoid that for `Stream` and `EphemeralStream`'s `foldMapRight1Opt` by taking advantage of their structure.
=> Lazy non-empty right fold for streams; more efficient left fold too

core/src/main/scala/scalaz/FreeT.scala, tests/src/test/scala/scalaz/FreeTTest.scala
~~This is based off a pending PR #1157  to avoid merge conflicts. See only the latest commit for the stack-safety fix. I can rebase if necessary.~~
=> Make FreeT#hoist and FreeT#interpret stack safe

core/src/main/scala/scalaz/Map.scala, tests/src/test/scala/scalaz/MapTest.scala
Our implementation is based on v0.4.0. Since haskell's Data.Map of v0.5.7.1 has a lot of improvement compared to that of v0.4.0, we can expect a better result by catching up the latest haskell's implementation.
As Milan Straka(a.k.a foxik from haskell/containers) and Kazu Yamamoto discussed [1, 2], we can expect insertion speed-up and deletion slow-down by changing the value. Actually only valid delta value with `ratio = 2` is 3 or 4 as proved by Yoichi Hirai and Kazuhiko Yamamoto, and Milan Straka[3, 4].
One justification to set 3, I think, is we'd expect more insertion operations than deletion operations. Even though deletion is executed more than the number of times insertion is called, it doesn't really hurt us as it means we do deletion onto an empty map which indicates `O(1)`.
[1] …
=> Improve IMap based on haskell/containers v0.5.7.1 updates

tests/jvm/src/test/scala/scalaz/NonEmptyListTestJVM.scala, tests/jvm/src/test/scala/scalaz/StrictTreeTestJVM.scala, tests/jvm/src/test/scala/scalaz/TreeTestJVM.scala
This reduces the running time of `testsJVM/test` on my laptop from 622s to 87s and avoids 7 `OutOfMemoryError`s during tests.
=> Reduce running time of tests.

core/src/main/scala/scalaz/syntax/AssociativeSyntax.scala, tests/src/test/scala/scalaz/AssociativeTest.scala
before
```
scala> import scalaz._, std.tuple._, syntax.associative._
import scalaz._
import std.tuple._
import syntax.associative._
scala>  val a1 = (1, (2, 3))
a1: (Int, (Int, Int)) = (1,(2,3))
scala> val b1 = a1.reassociateLeft
<console>:26: error: could not find implicit value for parameter ev: scalaz.Leibniz.===[(Int, Int),(TT, C)]
val b1 = a1.reassociateLeft
^
scala> val b1 = a1.reassociateLeft[Int, Int]
b1: ((Int, Int), Int) = ((1,2),3)
```
after
````
scala> import scalaz._, std.tuple._, syntax.associative._
import scalaz._
import std.tuple._
import syntax.associative._
scala>  val a1 = (1, (2, 3))
a1: (Int, (Int, Int)) = (1,(2,3))
scala> val b1 = a1.reassociateLeft
b1: ((Int, Int), Int) = ((1,2),3)
```
=> use Liskov instead of Leibniz in AssociativeOps

base/src/main/scala/typeclass/TraversableFunctions.scala, base/src/main/scala/typeclass/TraversableSyntax.scala, prelude/src/main/scala/Prelude.scala
Should be the last one remaining where it was mixed with syntax (preventing inclusion in `Prelude`).
=> Extract `TraversableFunctions`.

core/src/main/scala/scalaz/Arrow.scala
This is a continuation of #1237
=> Make swap a method of Arrow, so that an instance of Arrow may override `swap`

core/src/main/scala/scalaz/Dequeue.scala, tests/src/test/scala/scalaz/DequeueTest.scala
This PR proposes a small bugfix to `Dequeue.toBackIList`.  The issue is that when working with a `FullDequeue` with more than 2 elements, the order of the resulting `IList` is incorrect as shown in this REPL session:
````
scala> val empty = Dequeue.empty[Char]
empty: scalaz.Dequeue[Char] = EmptyDequeue
scala> ('a' +: 'b' +: 'c' +: empty).toIList
res0: scalaz.IList[Char] = [a,b,c]
scala> ('a' +: 'b' +: 'c' +: empty).toBackIList
res1: scalaz.IList[Char] = [c,b,a]
scala> ('a' +: 'b' +: 'c' +: 'd' +: empty).toIList
res2: scalaz.IList[Char] = [a,b,c,d]
scala> ('a' +: 'b' +: 'c' +: 'd' +: empty).toBackIList
res3: scalaz.IList[Char] = [d,b,c,a]
````
In `res3` the `front` list of the `FullDequeue` is `a :: b :: c :: Nil`.  The head correctly becomes the last element but `front.tail` must be …
=> Dequeue.toBackIList bugfix

core/src/main/scala/scalaz/EitherT.scala
Static overload resolution (which also governs which competing implicit
to select) was buggy in Scala 2.11 when a pair of competing methods had
a higher-kinded type parameter.
Here's a minimization of the bug:
```
trait M1[A]; trait M2[A] extends M1[A]
trait N1[A[_]]; trait N2[A[_]] extends N1[A]
object Test {
type D = DummyImplicit
def m[A](implicit d: D): M1[A] = ???
def m[A](implicit d1: D, d2: D): M2[A] = ???
m // not ambiguous M1[_] <:< M2[_]
def n[A[_]](implicit d: D): N1[A] = ???
def n[A[_]](implicit d1: D, d2: D): N2[A] = ???
n // was not ambiguous in 2.11:
// existentialAbtraction(A :: Nil, N2[A]) did not notice that `N2[A]` contained
// `A` (because it was eta expanded to [_]A[_] before matching for `case TypeRef(_, ASymbol, _)`)
}
```
This inconsistency will be plugged in Scala …
=> Adapt to fix in overload resolution in Scala 2.12

core/src/main/scala/scalaz/Free.scala
Currently testing this against Scala 2.12: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/
I've tried to leave things binary compatible, so the layout of implicits looks a little awkward.
Here's an isolated look at how the bugfix in overload resolution applied here:
```scala
class C {
sealed abstract class Free[S[_], A]
type Trampoline[A] = Free[Function0, A]
trait Monad[M[_]]
// #1
def instance      : Monad[Trampoline] = ???
// #2
def instance[S[_]]: Monad[({type f[x] = Free[S, x]})#f] = ???
instance // picks #1 after bug fix in Type#contains, used to be ambiguous
}
```
=> Another adaptation to bugfix in Scala 2.12 overload resolution

effect/src/main/scala/scalaz/effect/RegionT.scala
RegionT is a legal monad transformer, but it didn't have a MonadTrans instance defined, so I added it.
=> Add transformer instance for RegionT (via Hoist)

core/src/main/scala/scalaz/EitherT.scala, core/src/main/scala/scalaz/Kleisli.scala, core/src/main/scala/scalaz/ListT.scala, core/src/main/scala/scalaz/MaybeT.scala, core/src/main/scala/scalaz/OptionT.scala, core/src/main/scala/scalaz/ReaderWriterStateT.scala, core/src/main/scala/scalaz/StateT.scala, core/src/main/scala/scalaz/TheseT.scala, core/src/main/scala/scalaz/UnwriterT.scala, core/src/main/scala/scalaz/WriterT.scala, effect/src/main/scala/scalaz/effect/MonadCatchIO.scala, effect/src/main/scala/scalaz/effect/RegionT.scala
Added the `mapT` functions to the following transformers, as explained in https://github.com/scalaz/scalaz/issues/1244
- The `hoist` function is a special case of `mapT` (`hoist` is `mapT` with natural transformation), so I rewrote those.
- Also, updated TheseT's MonadCatchIO instance to be more concise, using mapT.
- `Kleisli` and `StateT` already had the functionality, called `mapK`, where the `K` I think comes from `Kleisli` (confusingly). For these, I just provided a `mapT` alias while keeping the old ones for compatibility.
=> Add mapT to monad transformers (#1224)

core/src/main/scala/scalaz/std/Map.scala
`Map#transform` only allows value updating, so potentially can be implemented without reindexing keys.  As far as I know, the standard library doesn't do this, but [it is possible](https://bitbucket.org/S11001001/record-map/src/4e9a60fb15f5b4567a379e14837826d1d465fa39/src/main/scala/Record.scala?at=default&fileviewer=file-view-default#Record.scala-180:188).  It's also a little nicer to not bother to return the key as well.
This makes the `Map` functions use `transform` where they were calling `map` but always returning the same key.
=> Use transform instead of map where possible on stdlib Maps

core/src/main/scala/scalaz/Const.scala, core/src/main/scala/scalaz/Coyoneda.scala, core/src/main/scala/scalaz/EitherT.scala, core/src/main/scala/scalaz/FingerTree.scala, core/src/main/scala/scalaz/Free.scala, core/src/main/scala/scalaz/FreeAp.scala, core/src/main/scala/scalaz/FreeT.scala, core/src/main/scala/scalaz/IdT.scala, core/src/main/scala/scalaz/IndexedContsT.scala, core/src/main/scala/scalaz/Isomorphism.scala, core/src/main/scala/scalaz/Kleisli.scala, core/src/main/scala/scalaz/LazyEitherT.scala, core/src/main/scala/scalaz/LazyOptionT.scala, core/src/main/scala/scalaz/Lens.scala, core/src/main/scala/scalaz/ListT.scala, core/src/main/scala/scalaz/MaybeT.scala, core/src/main/scala/scalaz/NaturalTransformation.scala, core/src/main/scala/scalaz/OptionT.scala, core/src/main/scala/scalaz/ReaderWriterStateT.scala, core/src/main/scala/scalaz/StateT.scala, core/src/main/scala/scalaz/StoreT.scala, core/src/main/scala/scalaz/StreamT.scala, core/src/main/scala/scalaz/TheseT.scala, core/src/main/scala/scalaz/TracedT.scala, core/src/main/scala/scalaz/WriterT.scala, effect/src/main/scala/scalaz/effect/RegionT.scala, effect/src/main/scala/scalaz/effect/ST.scala, iteratee/src/main/scala/scalaz/iteratee/IterateeT.scala, project/build.scala
fix #1258
https://github.com/non/kind-projector/tree/v0.9.0#polymorphic-lambda-values
=> use polymorphic lambdas

core/src/main/scala/scalaz/MonadPlus.scala, core/src/main/scala/scalaz/syntax/MonadPlusSyntax.scala, tests/src/test/scala/scalaz/MonadPlusTest.scala
I was reimplementing something similar to Haskell's `lefts` and `rights` but @tpolecat pointed out that there was already `separate` in MonadPlus which already does the same and it's more general.
`lefts` and `rights` were already present in `MonadPlus` but were private, so this commit exposes them publicly.
=> Add lefts and rights functions to MonadPlus

core/src/main/scala/scalaz/EphemeralStream.scala
I agree with @dmitryleskov's [conclusions about the standard use of weak memoization for `EphemeralStream`](http://blog.dmitryleskov.com/programming/scala/stream-hygiene-iii-scalaz-ephemeralstream-fills-quite-a-canyon/); it's unnecessary churn for most applications, especially when building "wholemeal"—memoizing the final stream may be desirable, but almost certainly not the intermediates.  And it's impossible to "opt out".
This flips the memoization to "opt in"; you can invoke `.memoized` and the whole stream will be memoized.  Otherwise, it will be treated just like an ordinary by-name cons list.
There are no binary compatibility breaks, but the behavior change may discourage backporting.
Incidentally, `EphemeralStream` is worth comparing to #1193.
=> Only memoize EphemeralStream on request (#memoized).

core/src/main/scala/scalaz/std/List.scala, core/src/main/scala/scalaz/std/Vector.scala
The `Traverse` instance for the standard `List` converts it into an `IList`, then a `DList` of just that `IList`, then an `IList` again from that, which it then ultimately `(reverse . foldLeft)`s. Instead, I `(reverse . foldLeft)` the list directly. `Vector`'s traverse instance makes a bigger improvement, because it doesn't even require the `reverse` to be efficient.
I do not believe this PR is as efficient as the schemes proposed by @S11001001 in #1022 (if it were extended to standard `List`) or #1023, seeing as his seems to reduce the total number of `ap` calls, but this at least avoids unnecessary allocations.
=> Reduce allocations in traverse for list and vector

core/src/main/scala/scalaz/Free.scala, example/src/main/scala/scalaz/example/TrampolineUsage.scala, tests/src/test/scala/scalaz/FreeTest.scala
This is in line with previous changes to drop the `Functor` constraint from `Free`.
The signature has changed from
```scala
def foldRun[B](b: B)(f: (B, S[Free[S, A]]) => (B, Free[S, A]))(implicit S: Functor[S]): (B, A)
```
to
```scala
def foldRun[B](b: B)(f: λ[α => (B, S[α])] ~> (B, ?)): (B, A)
```
I also added test that `foldRun` can be used to implement a stack-safe state monad. (Previously, `foldRun` was not tested at all.)
**EDIT:** Also added `foldRunM`:
```scala
def foldRunM[M[_], B](b: B)(f: λ[α => (B, S[α])] ~> λ[α => M[(B, α)]])(implicit M0: Applicative[M], M1: BindRec[M]): M[(B, A)]
```
and tests that show that it can be used to implement stack-safe `StateT`.
=> Reimplement Free#foldRun without the Functor contraint.

concurrent/src/main/scala/scalaz/concurrent/Task.scala
When calling Task.gatherUnordered without exceptionCancels set, Task was then calling Nondeterminism[Task].reduceUnordered, which is the derived method from the parent instance.  This is non optimized for Task, and ended up being much slower than when calling Nondeterminism[Task].gatherUnordered. 
I've changed it to call the same method when you aren't trying to cancel running Tasks, as the behavior is the same but now calling either Task.gatherUnordered has the same performance as Nondeterminism[Task].gatherUnordered.
=> Fix for #997 (Use Task's gatherUnordered instead of derived method)

core/src/main/scala/scalaz/Cofree.scala
`CofreeBind` evaluates `c.tail` for no reason.
=> Make CofreeBind sufficiently lazy

core/src/main/scala/scalaz/FreeT.scala
`Free#resume` returns
``` scala
S[Free[S, A]] \/ A
```
so I flipped the disjunction in `FreeT#resume` return type to
``` scala
M[S[FreeT[S, M, A]] \/ A]
```
to closely match `Free#resume`. It also makes slightly more sense to have the "done" case in the "right" position.
/cc @puffnfresh
=> Align the return type of FreeT#resume with that of Free#resume.

core/src/main/scala/scalaz/Cofree.scala
Moving that functor. `mapBranching` does not use the `T` functor. `mapBranching` and `mapBranchingT`, assuming both functors exist and are lawful, always return the same result. All this allows for is a choice of constraint.
=> Remove Cofree.mapBranching constraint, add Cofree.mapBranchingT

core/src/main/scala/scalaz/Lens.scala, core/src/main/scala/scalaz/StoreT.scala
- LensFamily:
- `setf`: functor-accepting version of `set`, analogous to how
`modf` already is a functor-accepting version of `mod`.
- IndexedStoreT:
- `putf`: functor-accepting version of `put`.
- `putsf`: functor-accepting version of `puts`.
=> Add some Lens and Store methods accepting arguments wrapped in a funtor.

concurrent/src/main/scala/scalaz/concurrent/Future.scala, concurrent/src/main/scala/scalaz/concurrent/Task.scala
I was doing some more interesting things in Future when I kept seeing these, decided to remove them.  This should be non controversial.
=> removing the methods in Future/Task that were deprecated in 7.2

core/src/main/scala/scalaz/MonadState.scala, tests/src/test/scala/scalaz/StateTTest.scala
I was using a stack of monads with a `StateT` and found that when I need a `MonadState` I can't get one derived on a `MonadTrans`.
Not sure if this is useful, but thought it might help someone.
=> Add derivation for MonadState using MonadTrans

core/src/main/scala/scalaz/Tag.scala, core/src/main/scala/scalaz/package.scala, tests/src/test/scala/scalaz/TagTest.scala
By replacing the structural type with an abstract [existential] type, the `subst`/`unsubst` code sees that a tagged type is equal to the untagged type, so it doesn't need to cast.
* Now, `subst` cannot be used to derive `unsafeCoerce` in concert with singleton type patterns.
* Tags/untags no longer form an optimization barrier for inlining optimizers, because there are neither internal nor external inconsistencies when tagging.
=> Cast-free type tags

core/src/main/scala/scalaz/Inject.scala, tests/src/test/scala/scalaz/InjectTest.scala
This makes it possible to pattern-match on unknown Coproducts, given
appropriate `Inject` constraints.
E.g.
```scala
def foo[F[_], A](fa: F[A])(implicit In: SomeComponent :<: F) = fa match {
case In(SomeComponent(_)) => true
case _ => false
}
```
=> Add `Inject.unapply`.

core/src/main/scala/scalaz/Applicative.scala, example/src/main/scala/scalaz/example/TraverseUsage.scala, tests/src/test/scala/scalaz/TraverseTest.scala
The instance is too "default instance"-y, and incoherent to boot; a compiler error is better.
This effectively reverts 186693a3869b9c887452911b6bc51d47038a3ee0.
=> Make Monoid[M] => Applicative[λ[α => M]] no longer implicit

effect/src/main/scala/scalaz/effect/IO.scala, effect/src/main/scala/scalaz/effect/ST.scala
The [linked paper](http://research.microsoft.com/en-us/um/people/simonpj/papers/lazy-functional-state-threads.ps.Z) states (section 6.2.2) two reasons for passing the state around, none of which seems to apply in Scala:
> Firstly, the compiler “shakes the code around” quite considerably: is it possible that it might somehow end up changing the order in which the primitive operations are performed? No, it is not. The input state of each primitive operation is produced by the preceding operation, so the ordering between them is maintained by simple data dependencies of the explicit state, which are certainly preserved by every correct program transformation.
Since Scala is not pure, the compiler is already restricted in reordering the code, particularly wrt. reads and writes to mutable …
=> Don't pass around fictitious state (IvoryTower) in ST.

core/src/main/scala/scalaz/FreeT.scala, tests/src/test/scala/scalaz/FreeTTest.scala
=> Fix the `plus` operation for `FreeT`

core/src/main/scala/scalaz/Leibniz.scala
`ev.flip` is more convenient than `Leibniz.symm(ev)`.
The latter also sometimes requires explicitly specifying type parameters.
=> Add method Leibniz#flip.

project/build.scala
Is it perhaps time to change the default Scala version to 2.11.8? This will not have much impact, since `scalaz` is cross-built anyway, but `scalaVersion` happens to be the version that is used by `publishLocal`. So I suppose if most devs are on 2.11.8, this makes sense.
=> Change default Scala version to 2.12.1.

core/src/main/scala/scalaz/ISet.scala
The main point I'm trying to make is that it is a requirement on the _functions_ passed to `map`, rather than a requirement on the `Order` instance of the target type (as the previous comment was suggesting).
=> Update comment at ISet#map about Functor requirements.

project/build.properties, project/build.scala
Fixes typelevel/scala#135.
What should we do with `"org.scala-lang.modules"`? Thanks!
=> Change CrossVersion.full to CrossVersion.patch

core/src/main/scala/scalaz/syntax/ContTOps.scala, core/src/main/scala/scalaz/syntax/Syntax.scala, example/src/main/scala/scalaz/example/ContTUsage.scala
Add syntax
- `ma.cps[R]` to convert `M[A]` to `ContT[M, R, A]`
- `ma.cps_` to convert `M[A]` to `ContT[M, Unit, A]`
=> ContT syntax.

core/src/main/scala/scalaz/Either.scala
=> Scala 2.12 has right-biased either; reference this in \/ doc

core/src/main/scala/scalaz/MonadTrans.scala, core/src/main/scala/scalaz/StreamT.scala, core/src/main/scala/scalaz/syntax/MonadTransSyntax.scala, core/src/main/scala/scalaz/syntax/Syntax.scala, example/src/main/scala/scalaz/example/MonadTransUsage.scala
Add method
```scala
trait MonadTrans[F[_[_], _]] {
def wrapEffect[G[_]: Monad, A](a: G[F[G, A]]): F[G, A] =
apply[G].join(liftM(a))
}
```
which is a generalization of the [`wrapEffect` method we have on `StreamT`](https://github.com/scalaz/scalaz/blob/f53658f4f5218622949d1f72a32f1bf82c416e0b/core/src/main/scala/scalaz/StreamT.scala#L304) to any monad transformer.
Added syntax allows to use it as a postfix operator:
```scala
val ms: M[StreamT[M, A]] = ???
val s: StreamT[M, A] = ms.wrapEffect
```
Note: the syntax would be usable for more monad transformers if we adressed #1305.
=> Add method MonadTrans#wrapEffect plus syntax for it.

core/src/main/scala/scalaz/Cord.scala, core/src/main/scala/scalaz/Either.scala, core/src/main/scala/scalaz/EitherT.scala, core/src/main/scala/scalaz/FingerTree.scala, core/src/main/scala/scalaz/StreamT.scala, core/src/main/scala/scalaz/Validation.scala, core/src/main/scala/scalaz/WriterT.scala, iteratee/src/main/scala/scalaz/iteratee/EnumeratorT.scala
* Deprecate :?>> on \/, EitherT, Validation; suggest new `foldConst` instead.
* Remove => on :-suffixed methods where users are unlikely to have been bothered by these never having been lazy in the first place.
Addresses #528.
=> Remove by-nameness from :-ending methods, due to SI-1980

core/src/main/scala/scalaz/syntax/ApplySyntax.scala, tests/src/test/scala/scalaz/ApplyTest.scala
Addresses #1020.
I also added a few unit tests within this PR.
```
Welcome to Scala version 2.10.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112).
import scalaz.syntax._
import scalaz.Scalaz._
scala> none[Int] *> ???
res1: Option[Nothing] = None
```
=> Make *> non-strict in its second argument.

core/src/main/scala/scalaz/NaturalTransformation.scala
Closes #1222 
~~I couldn't add this directly on `NaturalTransformation` because of the variance markers on that trait for `F[_]` and `G[_]`~~
=> Adds `or` to NaturalTransformation

core/src/main/scala/scalaz/Cofree.scala, core/src/main/scala/scalaz/Free.scala, core/src/main/scala/scalaz/Zap.scala
`resumeC` returns `Coyoneda[S, Free[S, A]]` where `resume` returns `S[Free[S, A]]`.
```scala
def resume(implicit S: Functor[S]):          S[Free[S,A]] \/ A
def resumeC:                        Coyoneda[S,Free[S,A]] \/ A
```
Used to remove `Functor` constraints elsewhere.
=> Add method Free#resumeC, a variant of resume that doesn't require Functor.

core/src/main/scala/scalaz/Map.scala, tests/src/test/scala/scalaz/MapTest.scala
Map (==>>) should have a Band instance for A ==>> B if there is a Band[B].
=> Map (==>>) should have a Band instance

core/src/main/scala/scalaz/EitherT.scala, core/src/main/scala/scalaz/ListT.scala, core/src/main/scala/scalaz/MaybeT.scala, core/src/main/scala/scalaz/OptionT.scala, core/src/main/scala/scalaz/WriterT.scala, tests/src/test/scala/scalaz/EitherTTest.scala, tests/src/test/scala/scalaz/ListTTest.scala, tests/src/test/scala/scalaz/MaybeTTest.scala, tests/src/test/scala/scalaz/OptionTTest.scala, tests/src/test/scala/scalaz/WriterTTest.scala
Given map(A => B) and flatMapF(A => G[F[B]) we should have mapF(A => G[B])
I also fixed an anomaly in the flatMapF signature of OptionT compared to the other transformers.
I also added a show instance for MaybeT.
This would break existing code, please review carefully.
=> Add mapF in analogy to flatMapF to Monad Transformers

project/ScalazBuild.scala
The macro recompile message is annoying and verbose, and I think we've sufficiently isolated the syntax macros by putting them in the meta project. This PR removes them.
=> Remove macro recompile message

build.sbt, project/ScalazBuild.scala
Move Scalaz 8 to a build.sbt-based build, because Build.scala-style definitions are deprecated and will be removed in SBT 1.0.
=> Move to build.sbt-based build definition

base/src/main/scala/typeclass/Phantom.scala, base/src/main/scala/typeclass/PhantomClass.scala, base/src/main/scala/typeclass/PhantomFunctions.scala, base/src/main/scala/typeclass/PhantomInstances.scala, base/src/main/scala/typeclass/PhantomSyntax.scala
Phantom-variant functors. All `F[A]`s with lawful `Functor[F]` *and* `Contravariant[F]` have no occurrences of `A` in their definition, and thus the `A` can be freely changed to any other `B` without changing the data within; the `A` is *phantom-variant*. More succinctly, all values of type `F[A]` are also values of type `F[B]` for all `A` and `B`, which is witnessed by `pmap[A, B](fa: F[A]): F[B]`. See http://typelevel.org/blog/2016/02/04/variance-and-functors.html.
Note that this has no laws further than `Functor[F]` and `Contravariant[F]`, which interact with one another. I'm not sure where `pmap` should go otherwise, if this is too large an obstacle to include this type class.
=> Phantom functor

core/src/main/scala/scalaz/IndexedContsT.scala
I am using continuation in RPC. I need to make it a case class in order to serialize it.
=> Make IndexedContsT a case class

core/src/main/scala/scalaz/Associative.scala, core/src/main/scala/scalaz/Isomorphism.scala, example/src/main/scala/scalaz/example/IsomorphismUsage.scala
not sure about the naming of `object`s; should `<=>` be used instead of `IsoSet`?
=> Add convenience constructors for <~> and <=>.

base/shared/src/main/scala/scalaz/Prelude.scala, base/shared/src/main/scala/scalaz/data/Forall.scala, base/shared/src/main/scala/scalaz/data/Forall2.scala, base/shared/src/main/scala/scalaz/data/package.scala, build.sbt, example/shared/src/main/scala/scalaz/example/ForallUsage.scala
Define `Forall[F[_]]` as an abstract type, privately implemented as
```scala
type Forall[F[_]] = F[Any]
```
A type alias is provided
```scala
type ∀[F[_]] = Forall[F]
```
Since `Forall[F]` is represented as `F[Any]`, care needs to be taken so that only truly parametric instances can be created. Two ways to create instances are provided:
1. From a "prototype", which is a Scalaz7-style universally quantified value:
```scala
def from[F[_]](p: Prototype[F]): Forall[F]
trait Prototype[F[_]] {
def apply[A]: F[A]
}
```
Prospectively, there could be convenient syntax for creating `Prototype`s via non/kind-projector#54.
Note that creation via a prototype requires an allocation of a short-lived object (the prototype), but the resulting `Forall[F]` value is unboxed. (Perhaps that one allocation …
=> Unboxed Forall

meta/shared/src/main/scala/scalaz/meta/Ops.scala
Removes some boilerplate.
See http://docs.scala-lang.org/overviews/macros/bundles.html
Also upgrades some versions and drops the deprecated sbt.Build trait.
Feedback always welcome.
=> Redefine scalaz.meta.Ops as a macro bundle

base/shared/src/main/scala/scalaz/data/Forall.scala, base/shared/src/main/scala/scalaz/data/Leibniz.scala, base/shared/src/main/scala/scalaz/data/Maybe.scala, base/shared/src/main/scala/scalaz/data/MaybeFunctions.scala, base/shared/src/main/scala/scalaz/typeclass/Liskov.scala
Use polymorphic singleton values in order to avoid either of
- allocating a new instance for each type argument; or
- using `asInstanceOf` to cast the singleton object to the desired type.
```scala
case class Empty[A]() extends Maybe[A]
```
👎  Allocates a new `Empty[T]` instance for each type `T`.
```scala
case object Empty extends Maybe[Nothing]
```
👎  Use `Empty.asInstanceOf[Maybe[T]]` to get an empty instance of `Maybe[T]`. (Note that `Maybe` is assumed to be invariant.)
```scala
class Empty[A] private[Maybe]() extends Maybe[A]
val Empty: ∀[Empty] = ∀.of[Empty].from(new Empty)
```
To get an empty instance of `Maybe[T]`, use
```scala
Empty[T]
```
which doesn't allocate any new objects (assuming zero-cost syntax that adds the `.apply[T]` method to `∀[Empty]`).
👍  Avoids both downsides of …
=> Polymorphic singletons

base/shared/src/main/scala/scalaz/data/Forall.scala
Added three rules:
```scala
∀[F] <: F[A]
A <: ∀[λ[α => A]]
F[_] <: G[_]   implies   ∀[F] <: ∀[G]
```
These correspond, respectively, to rules (4), (5) and (3) from
http://www.sciencedirect.com/science/article/pii/S0890540101929505
---
I wanted to add another one,
```scala
∀α.G[F[α]] <: G[∀α.F[α]]  // for G covariant and F any-variant
```
which would correspond to rule (6) from the linked paper and to quantifier distributivity in logic over any covariant position, but couldn't come up with proper justification for it. I still think it's valid in Scala, just pending a good argument why.
=> Interaction of universal quantification and subtyping.

base/shared/src/main/scala/scalaz/data/ACatenable1.scala, base/shared/src/main/scala/scalaz/data/AList.scala, base/shared/src/main/scala/scalaz/data/AList1.scala, base/shared/src/main/scala/scalaz/data/AMaybe.scala, base/shared/src/main/scala/scalaz/data/APair.scala, base/shared/src/main/scala/scalaz/data/balanced.scala, base/shared/src/main/scala/scalaz/data/package.scala, project/ScalazBuild.scala
- **`AMaybe[F[_, _], A, B]`:** Similar to `Maybe[F[A, B]]`, but the empty case witnesses type equality between `A` and `B`.
- **`APair[F[_], G[_]]`:** Isomorphic to `(F[A], G[A]) forSome { type A }`, but more robust with respect to type inference.
- **`AList[F[_, _], A, B]`:** Type-aligned list. Empty list witnesses type equality between `A` and `B`.
- **`AList1[F[_, _], A, B]`:** Non-empty type-aligned list.
- **`ACatenable1[F[_, _], A, B]`:** Non-empty type-aligned sequence with _O(1)_ `cons`, `snoc` and concatenation.
All sequence data types (`AList`, `AList1`, `ACatenable1`) are folded in balanced binary fashion (analogous to what @S11001001 did in #1022).
The [P∀scal compiler plugin](https://github.com/TomasMikula/pascal) was added to help with creation of some polymorphic values.
=> Type-aligned data types.

core/src/main/scala/scalaz/Unapply.scala, tests/src/test/scala/scalaz/UnapplyTest.scala
Remove implicit `Unapply` instances that under `-Ypartial-unification` are covered by another case.
Add tests that the cases covered by the removed instances are still covered.
Where the clients previously depended on an instance that is now removed, they will be required to enable `-Ypartial-unification`.
=> Remove implicit Unapply instances that under -Ypartial-unification are covered by another case.

base/shared/src/main/scala/scalaz/data/Fix.scala, base/shared/src/main/scala/scalaz/data/package.scala
Non-boxing implementation of `Fix`.
This is the part of #1455 (`IList` via `Fix`) which is independent of `IList` and useful on its own.
=> Fix data type

core/src/main/scala/scalaz/Apply.scala, core/src/main/scala/scalaz/Zip.scala, tests/src/test/scala/scalaz/ZipTest.scala
- In `apN`, avoid currying a function in multiple steps, creating intermediate, intermediately curried functions.
- In `applyN`, avoid constructing and deconstructing intermediate tuples.
As a bonus, the implementation is also shorter and more regular.
=> Simplify and optimize apN and applyN

base/shared/src/main/scala/scalaz/data/Forall.scala, base/shared/src/main/scala/scalaz/data/Forall2.scala, base/shared/src/main/scala/scalaz/data/IList.scala, base/shared/src/main/scala/scalaz/data/Maybe2.scala, base/shared/src/main/scala/scalaz/data/package.scala, build.sbt, example/shared/src/main/scala/scalaz/example/Maybe2Usage.scala
This is in the same spirit as `Maybe` in #1450.
Things to note:
- `uncons` is just `Fix.unfix`, which is identity.
- `IsCovariant[IList]` instance is created without (directly) using any unsafe operations (like `asInstanceOf` or `Liskov.unsafeForce`).
- Pattern matching is available (via `uncons(as) match { ... }`; though this can't be used in nested patterns).
The major problem, as with #1450, is the lack of companion object to look up typeclass instances.
To match the memory efficiency of `scala.List`, we would have to switch to a specialized implementation of `Option2[A, B]` instead of `Option[(A, B)]` to avoid the extra `Tuple2` instance.
=> [WIP] Sketch of IList with invariant interface and covariant implementation.

core/src/main/scala/scalaz/Foldable.scala, core/src/main/scala/scalaz/IList.scala, core/src/main/scala/scalaz/NonEmptyList.scala, core/src/main/scala/scalaz/std/Iterable.scala, core/src/main/scala/scalaz/std/List.scala, core/src/main/scala/scalaz/std/Set.scala, core/src/main/scala/scalaz/std/Stream.scala, core/src/main/scala/scalaz/std/Vector.scala
Just a lot of factoring to make the `scalaz.std` code less boring to read, not to mention get much better method specialization coverage.
Also includes related "to is almost always better than toList/toVector/toSet; use it"; if you like nothing else from this PR you should like this. bba9442
There's probably more to do here.
=> Factor stdlib collections' instances

core/src/main/scala/scalaz/Dequeue.scala, core/src/main/scala/scalaz/package.scala, example/src/main/scala/scalaz/example/Foldable1Usage.scala
NonEmptyList should be used instead. Having a type alias which provides less
behaviour is a bit confusing.
Fixes #1507
=> Remove NonEmptyIList

concurrent/src/main/scala/scalaz/concurrent/Task.scala, core/src/main/scala/scalaz/EphemeralStream.scala, core/src/main/scala/scalaz/Reducer.scala
This make EphemeralStream foldLeft/foldRight accept uncurried function.
Both args are always applied at the same times anyway.
This make it closer to Foldable api and should improve perf a little.
Also changed EphemeralStream reverse implementation to skip List creation.
This also allows to preserve head cell laziness.
=> Uncurry ephemeralstream fold and Reducer constructors

core/src/main/scala/scalaz/ReaderWriterStateT.scala, core/src/main/scala/scalaz/StateT.scala
This adds MonadError instances given a MonadError instance for StateT
and ReaderWriterStateT.
This implements #1396.
=> Add MonadError instances for StateT and RWST

base/shared/src/main/scala/scalaz/Prelude.scala, base/shared/src/main/scala/scalaz/data/AMaybe.scala, base/shared/src/main/scala/scalaz/data/AMaybeInstances.scala, base/shared/src/main/scala/scalaz/data/ConstInstances.scala, base/shared/src/main/scala/scalaz/data/DisjunctionInstances.scala, base/shared/src/main/scala/scalaz/data/Maybe.scala, base/shared/src/main/scala/scalaz/data/Maybe2.scala, base/shared/src/main/scala/scalaz/typeclass/Show.scala, base/shared/src/main/scala/scalaz/typeclass/ShowInstances.scala, base/shared/src/main/scala/scalaz/typeclass/ShowSyntax.scala, example/shared/src/main/scala/scalaz/example/ShowUsage.scala
It's a very useful typeclass if you have an `Any#toString`-shaped hole in your cornea. Someone seems to have made a file for it and then never done anything with it. This resurrects it as a typical typeclass, with syntax, instances, usage examples, &c.
=> Show `Show` some love.

example/shared/src/main/scala/scalaz/example/DisjunctionUsage.scala
(This needs a `scalaz8` label, please)
This adds a simple example for usage of `Disjunction`.
I assume we are going to use the example project for some form of future documentation, so I am starting to contribute here...
=> Disjunction: Add usage example

base/shared/src/main/scala/scalaz/Prelude.scala, base/shared/src/main/scala/scalaz/typeclass/ApplySyntax.scala, base/shared/src/main/scala/scalaz/typeclass/BindSyntax.scala, base/shared/src/main/scala/scalaz/typeclass/ChoiceSyntax.scala, base/shared/src/main/scala/scalaz/typeclass/CobindSyntax.scala, base/shared/src/main/scala/scalaz/typeclass/ComonadSyntax.scala, base/shared/src/main/scala/scalaz/typeclass/ComposeSyntax.scala, base/shared/src/main/scala/scalaz/typeclass/FoldableSyntax.scala, base/shared/src/main/scala/scalaz/typeclass/FunctorSyntax.scala, base/shared/src/main/scala/scalaz/typeclass/InvariantFunctorSyntax.scala, base/shared/src/main/scala/scalaz/typeclass/Phantom.scala, base/shared/src/main/scala/scalaz/typeclass/PhantomSyntax.scala, base/shared/src/main/scala/scalaz/typeclass/ProfunctorSyntax.scala, base/shared/src/main/scala/scalaz/typeclass/SemigroupSyntax.scala, base/shared/src/main/scala/scalaz/typeclass/ShowSyntax.scala, base/shared/src/main/scala/scalaz/typeclass/StrongSyntax.scala, base/shared/src/main/scala/scalaz/typeclass/TraversableSyntax.scala, base/shared/src/test/scala/SyntaxResolutionTest.scala, meta/shared/src/main/scala/scalaz/meta/Ops.scala
Since 8.0.x won't support scala 2.10, there's no reason to bother using raw trees and `c.Expr`s all over the place. With this, it's possible to drop all the type parameters and write the impls in a somewhat less esoteric style (for when more shapes are inevitably needed).
The ops macros need to be blackbox, otherwise `f_0` won't fix the result type based on its type argument, and infer `Nothing`. It's not trivial to return a properly-typed tree if the return type is an arbitrary function of a cloud of types floating over the macro application, so it's easier to just accept the blackboxity and go ahead with unrestricted type inference.
Fixes #1542, so a ping to @NeQuissimus.
=> Modernize meta.Ops, adapt it to new useful shapes, and use it more.

core/src/main/scala/scalaz/Cord.scala
Pasted:
Please tell me if I'm missing something, because it looks like toString is terrible. It recreates the entire tree, it creates a huge Trampoline instance to suspend side effects, and the cardinal sin, it's more code than the simpler and more efficient solution.
Also, x.toString means boxing x before calling toString. String.valueOf could be a small optimization, but less boxing is never a bad thing.
=> Redux: Reduce unnecessary work in Cord#toString, Cord#:-, Cord#-:

example/src/main/resources/microsite/data/menu.yml, example/src/main/tut/data/Maybe.md, example/src/main/tut/data/Maybe2.md
Adding more examples. 
`Maybe2` is rather limited given #1538
=> [8.0.x] example: Add Maybe and Maybe2

base/shared/src/main/scala/scalaz/typeclass/ApplicativeSyntax.scala, base/shared/src/test/scala/SyntaxResolutionTest.scala, meta/shared/src/main/scala/scalaz/meta/Ops.scala
This allows for such syntax as `f.pure[F]` and (eventually) `err.raiseError[M]`.
After this I'll leave the macros alone for a while.
=> Add macro shape for OpsA-style syntax.

core/src/main/scala/scalaz/std/String.scala
Since there is no `Read` typeclass in Scalaz (nor should there be), `Show` becomes nearly lawless. That's okay if it's only used for debugging and never intended for serious serialization.
That said, here's an attempt at one law, which is reflected in the code change and alters the output of `.shows`:
> Law of String Identity: `String.shows == id`
=> Improved `Show` instance for String

core/src/main/scala/scalaz/Dequeue.scala, tests/src/test/scala/scalaz/DequeueTest.scala
There might be a reason these didn't exist before, but I didn't see any old issues about it.  If this gets approved, I'll backport to 7.2.x.
=> Monad Plus and Traverse instances for Dequeue

core/src/main/scala/scalaz/EitherT.scala, core/src/main/scala/scalaz/syntax/EitherTOps.scala, core/src/main/scala/scalaz/syntax/Syntax.scala, core/src/main/scala/scalaz/syntax/package.scala, tests/src/test/scala/scalaz/EitherTTest.scala
just some syntax sugar, close #1560 
presumably the `FromDisjunctionAux` hack needs to be used here to help with type inference somehow?
=> some convenient constructors for EitherT

.jvmopts, build.sbt
All the scalajs / scala-native stuff keeps getting in my way when I'm wanting to contribute, this should help most contributors.
The `sbt` script should read the `.jvmopts` file so contributors don't have to manually set up a memory limit. Without this, about 2 compile cycles is enough to OOM.
=> sbt build improvements for JVM contributors

core/src/main/scala/scalaz/Maybe.scala, tests/src/test/scala/scalaz/MaybeTests.scala
It's horrible, I hate it, but scala makes us do this if we want to avoid object allocations.
I'd quite like a compiler plugin (or a stock compiler optimisation) that does this automatically for zero parameter case classes.
close #1498
=> avoid object allocations from Maybe.Empty()

core/src/main/scala/scalaz/Dequeue.scala, core/src/main/scala/scalaz/IList.scala, core/src/main/scala/scalaz/ISet.scala, core/src/main/scala/scalaz/Map.scala, core/src/main/scala/scalaz/Maybe.scala
same deal as #1579 ... just as ugly but the runtime benefits are worth it.
=> Consistent use of case objects for invariant "empty" ADTs

project/build.scala
// @xuwei-k this adds a few more options that are used in other projects. Plus, by not **requiring** the credentials file to exist, the sbt credentials warning goes away for most contributors. If this is too much, I'd be happy to scale it back to just optional credentials.
Without this change ...
```
[warn] Credentials file /home/fommil/.ivy2/.credentials does not exist
[warn] Credentials file /home/fommil/.ivy2/.credentials does not exist
[warn] Credentials file /home/fommil/.ivy2/.credentials does not exist
[warn] Credentials file /home/fommil/.ivy2/.credentials does not exist
[warn] Credentials file /home/fommil/.ivy2/.credentials does not exist
[warn] Credentials file /home/fommil/.ivy2/.credentials does not exist
[warn] Credentials file /home/fommil/.ivy2/.credentials does not exist …
```
=> more options for injecting credentials

core/src/main/scala/scalaz/Memo.scala, tests/src/test/scala/scalaz/MemoTest.scala
close #1488 
`Memo` is a wonderful idea with terrible implementations.
- hide a public method that allows mutable state to escape
- delete two implementations (weakhashmap and listmap) because neither are useful. @S11001001 has already noted the poor performance of the former, whereas `ListMap` is just generally best avoided in my experience.
- fixes several bugs in the array implementations that made `Memo` turn total functions into partial functions.
- added some tests.
Really we need to kill the current stdlib implementations and replace with versions that use the scalaz Maps / trees and/or (for performance) the java fast concurrent collections, perhaps revisiting weak keys / values again.
=> some fixes for Memo

core/src/main/scala/scalaz/IList.scala, tests/src/test/scala/scalaz/IListTest.scala
close #1591 
this looks like it might be nice to backport to 7.2
=> convenient pattern matching for IList

core/src/main/scala/scalaz/ImmutableArray.scala
close #1506
these methods amount to directly manipulating the array. The user can do that themselves if they really want to do it, we shouldn't encourage it.
=> make ImmutableArray a little bit safer

example/src/main/resources/microsite/data/menu.yml, example/src/main/tut/typeclass/Applicative.md, example/src/main/tut/typeclass/Functor.md, example/src/main/tut/typeclass/Monoid.md
- Remove the `Category Theory` headings. We can figure out links to literature or so later
- Add `map` to the Applicative syntax
- Add an Applicative doc
I am also opening another ticket because when you look at the implementation of `ApplicativeSyntax.Ops`, it is rather strange to hop through all the "embedded" instances.
=> [8.0.x] example: Add Applicative

core/src/main/scala/scalaz/IList.scala, tests/src/test/scala/scalaz/IListTest.scala
~~following on from #1591 this adds an `unapplySeq`~~
This now backs out #1591... read on for the reasoning:
But I noticed that the matchers disables exhaustivity checking under https://github.com/scala/bug/issues/10660
There is precedent in `EphemeralStream` to allow this.
It's a tricky one, perhaps in combination with https://github.com/scalacenter/scalafix/issues/528 this may be allowed, but I'm starting to think that perhaps - from a fundamentalist point of view - we should remove the extractor I recently added (and reject this PR) and instead remove custom `unapply` that we have defined.
// @jdegoes may have an opinion here.
=> ~~moar~~ remove IList pattern matchers

core/src/main/scala/scalaz/StateT.scala, core/src/main/scala/scalaz/StoreT.scala, tests/src/test/scala/scalaz/StateTTest.scala, tests/src/test/scala/scalaz/StoreTTest.scala
I read http://comonad.com/reader/2018/the-state-comonad/ and decided to quickly bang this out.
I also tried generising for `{State,Store}T` but they'd both need typeclasses over `F[_]` on both sides of the dual line. Specifically, for a `Monad[StoreT[F, S, ?]]`, `peek` needs a `Comonad[F]` where as `Monad#point` needs `Point[F]`. And similarly, a `Comonad[StateT[F, S, ?]]` needs both `Bind[F]` and `copoint`.
=> Add Store monad and State comonad

concurrent/src/main/scala/scalaz/concurrent/Future.scala, concurrent/src/main/scala/scalaz/concurrent/Task.scala, core/src/main/scala/scalaz/Cord.scala, core/src/main/scala/scalaz/FingerTree.scala, core/src/main/scala/scalaz/Generator.scala, core/src/main/scala/scalaz/Nondeterminism.scala, core/src/main/scala/scalaz/Reducer.scala, core/src/main/scala/scalaz/std/String.scala, core/src/main/scala/scalaz/syntax/ReducerOps.scala, example/src/main/scala/scalaz/example/FingerTreeUsage.scala, iteratee/src/main/scala/scalaz/iteratee/Iteratee.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala, tests/jvm/src/test/scala/scalaz/concurrent/FutureTest.scala, tests/jvm/src/test/scala/scalaz/concurrent/TaskTest.scala, tests/src/test/scala/scalaz/FingerTreeTest.scala
(https://hackage.haskell.org/package/reducers)
Essentially lower the constraint on Reducer from Monoid to Semigroup.
Previous API was based on the now deprecated `monoids` package.
**Question 1**: should `Reducer` `snoc`/`cons` be lazy on their second argument, to match `semigroup` laziness behavior?
**Question 2**: should `Generator` be a type class, as in haskell? (ie. should we add implicit instances?)
**Question 3**: should we remove the unnecessary `Monoid` constraint on `mapTo`? IUC, this would mean that `mapTo` become the only primitive operation of `Generator` and that `mapFrom` is removed entirely.
this is  preliminary work to have a clean solution to  #1513 (`FromFoldable1`)
Above questions can be discussed here, but are probably better addressed (if needed) on separate PRs.
=>  Migrate Reducer in sync with reducer haskell lib

base/shared/src/main/scala/scalaz/typeclass/FunctorSyntax.scala
For Scalaz 8.
```
scala> import scalaz._
import scalaz._
scala> import Scalaz._
import Scalaz._
scala> Option(1)
res0: Option[Int] = Some(1)
scala> res0.fmap(_ + 1)
res1: Option[Int] = Some(2)
```
=> Add `fmap` as Functor syntax

core/src/main/scala/scalaz/std/String.scala
Unused predicate removed from `asNumber` function. This parameter is not used inside the function. `intChars` predicate is sufficient for handling number parsing errors because too big Float and Double parse to `Infitinity` and are handled in a separate code.
=> Simplified StringFunctions

core/src/main/scala/scalaz/std/Future.scala
this was deprecated some time ago and will no longer exist
in Scala 2.13.0-M4
this came up over at https://github.com/scala/scala/pull/6319
=> avoid deprecated PartialFunction.apply method

core/src/main/scala/scalaz/Either.scala, core/src/main/scala/scalaz/Maybe.scala
Maybe.orError, which is useful when wanting to flatten F[Maybe[A]] to an F[A] when operating inside a MonadError
=> Maybe.orError and \/.orRaiseError

core/src/main/scala/scalaz/syntax/EitherTOps.scala, tests/src/test/scala/scalaz/EitherTTest.scala
I regret adding this syntax in #1593
It is very confusing to have `.eitherT` direct to `EitherT.either` etc.
I'd really like to keep the syntax, but with different names. And I can't think of anything satisfactory.
Does anybody have any suggestions for the names? Or strong feelings to keep / delete?
=> remove the EitherT syntax

core/src/main/scala/scalaz/Either.scala, core/src/main/scala/scalaz/MonadError.scala, core/src/main/scala/scalaz/syntax/MonadErrorSyntax.scala, project/build.scala, tests/src/test/scala/scalaz/MonadErrorTest.scala
and some nice extra syntax
motivated by https://github.com/fthomas/refined/pull/447
can be used to provide a `MonadError` for typeclasses that only have type parameters in covariant position, giving us `.map`, `.emap` and more for free.
I'd like to test the MonadError laws on this derived instance... could somebody please help me do that?
=> derivation of MonadError for isomorphic things

core/src/main/scala/scalaz/unused.scala
#1669 
as in https://github.com/scala/bug/issues/10790
```scalaz
class unused extends deprecated("unused", "")
```
so we can turn on unused warnings in the build, with an easy way to opt out on a per-parameter basis.
Seems like a nice lint for us to have, and very useful to have as a dependency.
I'm not sure what the binary compatibility implications are for adding annotations to parameters.
=> add an `unused` annotation

core/src/main/scala/scalaz/Reducer.scala, core/src/main/scala/scalaz/syntax/ReducerOps.scala
- Added `unfoldlOpt`, `unfoldrOpt`: unfolds that don't require monoid.
- Removed `final` modifier from `unfoldl`.
=> Reducer: support unfolds without needing a monoid.

core/src/main/scala/scalaz/Bifoldable.scala, core/src/main/scala/scalaz/Bitraverse.scala, core/src/main/scala/scalaz/Endo.scala, core/src/main/scala/scalaz/FingerTree.scala, core/src/main/scala/scalaz/Foldable.scala, core/src/main/scala/scalaz/Traverse.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala, tests/src/test/scala/scalaz/EndoTest.scala, tests/src/test/scala/scalaz/FoldableTest.scala
and use it when implementing `foldRight` in term of `foldMap`, so that "by-name" evaluation semantic is preserved, potentially avoiding stack overflows.
=> Add a "by-name" variant of Endo

core/src/main/scala/scalaz/EitherT.scala, core/src/main/scala/scalaz/ImmutableArray.scala, core/src/main/scala/scalaz/Memo.scala
Otherwise you get messages like:
```
there was one deprecation warning (since prefer leftT; this method's meaning will change in scalaz 7.3)
```
... which I doubt was the intention.
=> Message first, version second in @deprecation messages.

core/src/main/scala/scalaz/Catchable.scala, core/src/main/scala/scalaz/Either.scala, core/src/main/scala/scalaz/EitherT.scala, core/src/main/scala/scalaz/Maybe.scala, core/src/main/scala/scalaz/Validation.scala, project/GenTypeClass.scala, tests/src/test/scala/scalaz/DisjunctionTest.scala, tests/src/test/scala/scalaz/MaybeTests.scala
close #1684 
When writing my book I realised two problems:
1. scalaz encourages the use of non referentially transparent `Throwable` in many places.
2. there is no principled way to interact with a legacy **deterministic** partial function that may throw an exception.
This PR addresses both, whilst retaining backwards binary compatibility in the 7.2 line:
1. deprecation warnings have been added to the worst offenders
2. `.fromPartial` function has been added to both `Maybe` and `\/` which discourages (although cannot completely ban) the use of non-referentially transparent stacktraces. scalafix should be able to help further.
For anything more complicated than this, the user should use `IO`.
=> do not encourage use of Throwable

concurrent/src/main/scala/scalaz/concurrent/Future.scala, concurrent/src/main/scala/scalaz/concurrent/Task.scala, core/src/main/scala/scalaz/EitherT.scala, core/src/main/scala/scalaz/Isomorphism.scala, core/src/main/scala/scalaz/Nondeterminism.scala, core/src/main/scala/scalaz/std/Future.scala, tests/jvm/src/test/scala/scalaz/EphemeralStreamTestJVM.scala, tests/jvm/src/test/scala/scalaz/concurrent/FutureTest.scala, tests/jvm/src/test/scala/scalaz/concurrent/TaskTest.scala, tests/jvm/src/test/scala/scalaz/std/FutureTest.scala
As suggested in #1627, I replaced the usage of Seq by IList.
=> 1627 replace seq

core/src/main/scala/scalaz/Either.scala, core/src/main/scala/scalaz/MonadError.scala, core/src/main/scala/scalaz/syntax/MonadErrorSyntax.scala
I wanted to do this in #1661 but couldn't because of bincompat.
The main motivation is that `emap` can be optimised efficiently by many typeclasses, e.g. decoders.
=> add MonadError.emap

base/shared/src/main/scala/scalaz/data/AFix.scala, base/shared/src/main/scala/scalaz/data/AList.scala, base/shared/src/main/scala/scalaz/data/AList1.scala, base/shared/src/main/scala/scalaz/data/AMaybe2.scala, base/shared/src/main/scala/scalaz/data/balanced.scala, base/shared/src/main/scala/scalaz/data/package.scala
We already implement `IList` as
```scala
type IList[A] = Fix[Maybe2[A, ?]]
```
This PR applies the same idea to the type-aligned list. To that end, type-aligned version of `Fix` is introduced:
```scala
type AFix[F[_[_, _], _, _], A, B] = F[AFix[F, ?, ?], A, B]
```
Then, we define type-aligned list as
```scala
type AList[F[_, _], A, B] = AFix[AMaybe2[F, ?[_, _], ?, ?], A, B]
```
The benefit is that `uncons` is just `unfix`, which is a no-op.
=> Implement AList via AFix (type-aligned version of Fix)

base/shared/src/main/scala/scalaz/Prelude.scala, base/shared/src/main/scala/scalaz/data/NotIs.scala, base/shared/src/main/scala/scalaz/data/Void.scala
The api is currently rather impoverished since the majority of the methods I have in `leibniz` require additional data types to be defined first. `NotIs` could be implemented as a newtype over `(A === B) => Void`, but I would like to first add a `@newtype` macro / compiler plugin to scalaz so that I don't pollute the code with unnecessary details of newtype encoding.
=> Void and denial inequality.

base/shared/src/main/scala/scalaz/Prelude.scala, base/shared/src/main/scala/scalaz/data/DisjunctionInstances.scala, base/shared/src/main/scala/scalaz/data/Maybe2.scala, base/shared/src/main/scala/scalaz/data/TheseInstances.scala, base/shared/src/main/scala/scalaz/data/package.scala, base/shared/src/main/scala/scalaz/typeclass/BifunctorClass.scala, base/shared/src/main/scala/scalaz/typeclass/BifunctorInstances.scala, base/shared/src/main/scala/scalaz/typeclass/BifunctorSyntax.scala, base/shared/src/test/scala/SyntaxResolutionTest.scala, example/src/main/resources/microsite/data/menu.yml, example/src/main/tut/typeclass/Bifunctor.md
Instances for `\/`, `\&/`, `Tuple2`, `Maybe2`, and the doc page.
I considered ways to have `Bifunctor[F]` => `[A] => Functor[F[A, ?]]` and `Bifunctor[F]` => `[B] => Functor[Op[F, B, ?]]`, but I couldn't get the instances to resolve properly so here's the typeclass and syntax if nothing else.
Apropos of https://github.com/scalaz/scalaz/pull/1700#discussion_r180098197 and the impending bifunctoral `IO`.
=> Add `Bifunctor`.

core/src/main/scala/scalaz/Foldable.scala, core/src/main/scala/scalaz/Maybe.scala, core/src/main/scala/scalaz/Monoid.scala, core/src/main/scala/scalaz/Plus.scala, core/src/main/scala/scalaz/PlusEmpty.scala, core/src/main/scala/scalaz/Reducer.scala, core/src/main/scala/scalaz/Semigroup.scala, core/src/main/scala/scalaz/std/AnyVal.scala, core/src/main/scala/scalaz/std/Stream.scala, core/src/main/scala/scalaz/syntax/FoldableSyntax.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazProperties.scala, tests/jvm/src/test/scala/scalaz/std/FutureTest.scala, tests/src/test/scala/scalaz/FoldableTest.scala, tests/src/test/scala/scalaz/MaybeTests.scala, tests/src/test/scala/scalaz/ReducerTest.scala, tests/src/test/scala/scalaz/std/AnyValTest.scala
Iterated multiplication may terminate when 0 is encountered.
This PR adds methods to `Semigroup`, `Monoid`, `Plus`, `PlusEmpty` that may take advantage of this fact.
It is demonstrated on a few cases:
- `Int` multiplication
- `Boolean` conjunction and disjunction
- `Maybe` "addition" (`Plus`)
Finally, these potentially short-circuiting methods can be used to implement `foldMap` (and `fold`, `psum`, `psumMap`) on many data structures. As a demonstration, it is done for `Stream`. As a result, we get **`foldMap` that is both stack-safe _and_ short-circuiting.**
Consequently, we may deprecate `msuml`, since there's no more need for it (`psum` used to be short-circuiting and `msuml` stack-safe, but now `psum` is both).
=> Unfolds and early termination

example/src/main/resources/microsite/data/menu.yml, example/src/main/tut/data/Disjunction.md, example/src/main/tut/typeclass/Debug.md, example/src/main/tut/typeclass/Functor.md, example/src/main/tut/typeclass/Monoid.md, example/src/main/tut/typeclass/Semigroup.md, example/src/main/tut/typeclass/index.md
Replacing #1607 with in-repo PR rather than fork. This way we can easily have other people contribute.
The goal of this PR is to document all the (currently existing) type classes into the `examples` module.
=> Document (very few) typeclasses

base/shared/src/main/scala/scalaz/typeclass/EqSyntax.scala, meta/shared/src/main/scala/scalaz/meta/Ops.scala
https://github.com/scalaz/scalaz/pull/1411 served as inspiration.
See https://github.com/scalaz/scalaz/pull/1711/files#diff-726e672735d618c9d9bc069c449a4fbeL6 for an example.
=> Symbolic ops macros.

core/src/main/scala/scalaz/Apply.scala, core/src/main/scala/scalaz/Maybe.scala, core/src/main/scala/scalaz/Plus.scala, core/src/main/scala/scalaz/PlusEmpty.scala, core/src/main/scala/scalaz/Reducer.scala, core/src/main/scala/scalaz/Semigroup.scala, core/src/main/scala/scalaz/std/List.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazProperties.scala, tests/src/test/scala/scalaz/MaybeTests.scala, tests/src/test/scala/scalaz/TraverseTest.scala
Some `Applicatives` have absorbing values (such as `Option`'s `None`) that may be used to terminate early.
This PR adds a method to `Apply` that may be overridden to take advantage of such short-circuiting.
```scala
trait Apply[F[_]] {
def unfoldrOpt[S, A, B](seed: S)(f: S => Maybe[(F[A], S)])(implicit R: Reducer[A, B]): Maybe[F[B]]
}
```
This PR then overrides this method for `Apply[Maybe]`. (This should be done for other Applicatives with absorbing elements as well.)
Finally, `List` traversal is implemented using this potentially short-circuiting method, resulting in **traversal that is both stack-safe and short-circuiting** (for short-circuiting Applicatives), resolving an old dilemma. (This should be done for other Traversables as well.)
~~(Note that the first 6 commits are from …
=> Applicative short-circuiting

.travis.yml
https://github.com/scalaz/scalaz/pull/1734#issuecomment-385627061
> each fastOptJS is memory-hungry
=> execute "test:fastOptJS" explicitly before test. avoid OutOfMemoryError

core/src/main/scala/scalaz/BijectionT.scala, core/src/main/scala/scalaz/Cokleisli.scala, core/src/main/scala/scalaz/EitherT.scala, core/src/main/scala/scalaz/Free.scala, core/src/main/scala/scalaz/IndexedContsT.scala, core/src/main/scala/scalaz/LazyEitherT.scala, core/src/main/scala/scalaz/Leibniz.scala, core/src/main/scala/scalaz/Lens.scala, core/src/main/scala/scalaz/PLens.scala, core/src/main/scala/scalaz/StreamT.scala, core/src/main/scala/scalaz/TracedT.scala, core/src/main/scala/scalaz/Unapply.scala, core/src/main/scala/scalaz/WriterT.scala, core/src/main/scala/scalaz/package.scala, core/src/main/scala/scalaz/syntax/BifunctorSyntax.scala, core/src/main/scala/scalaz/syntax/BindSyntax.scala, core/src/main/scala/scalaz/syntax/BitraverseSyntax.scala, core/src/main/scala/scalaz/syntax/Foldable1Syntax.scala, core/src/main/scala/scalaz/syntax/FoldableSyntax.scala, core/src/main/scala/scalaz/syntax/FunctorSyntax.scala, core/src/main/scala/scalaz/syntax/MonadPlusSyntax.scala, core/src/main/scala/scalaz/syntax/Traverse1Syntax.scala, core/src/main/scala/scalaz/syntax/TraverseSyntax.scala, core/src/main/scala/scalaz/syntax/std/Function1Ops.scala, core/src/main/scala/scalaz/syntax/std/Function2Ops.scala, core/src/main/scala/scalaz/syntax/std/ListOps.scala, example/src/main/scala/scalaz/example/TraverseUsage.scala, iteratee/src/main/scala/scalaz/iteratee/EnumeratorT.scala, iteratee/src/main/scala/scalaz/iteratee/IterateeT.scala, tests/src/test/scala/scalaz/UnapplyTest.scala
As suggested in fommil/fpmortals#49
I couldn't compile and test this on my local machine due to a "file name too long" error during compilation.
=> Replace all usages of "=:=" with "==="

core/src/main/scala/scalaz/EphemeralStream.scala, core/src/main/scala/scalaz/IList.scala, core/src/main/scala/scalaz/NonEmptyList.scala, core/src/main/scala/scalaz/std/List.scala, tests/src/test/scala/scalaz/FoldableTest.scala, tests/src/test/scala/scalaz/IListTest.scala, tests/src/test/scala/scalaz/NonEmptyListTest.scala, tests/src/test/scala/scalaz/std/ListTest.scala
I have a question regarding adding tests for the new implementations. I was unable to add a test for the NonEmptyList foldMap implementation to `NonEmptyListTest.scala` but was able to add corresponding tests for the other data structures. Is there something different about that data structure? Also, I was curious if adding more psumMap test cases utilizing the different data structures like I did made sense.
=> Issue #1706 - Potentially short-circuiting foldMap

core/src/main/scala/scalaz/NaturalTransformation.scala
backport @lloydmeta's `or`, but without the subtyping.
=> NaturalTransformation.or

core/src/main/scala/scalaz/syntax/IdOps.scala
This might seem superflous, but the problem I have is that when I want to flatMap or map over the result of a match statement
```
foo match {
...
}.flatMap {...}
```
the compiler complains unless I put some extra parens in.
```
{foo match {
...
}}.flatMap {...}
```
which looks very ugly and is just intrusive.
A fix I've been playing with is to do
```
foo.|> {
...
}.flatMap {...}
```
which is kinda weird because of the dot `.` when used with a symbolic operator. I settled on `switch` in my own code and I thought others might benefit.
Also this helps keep you honest as the type signature is `Function` not `PartialFunction` so I think it's a better alternative to `match`.
This is a candidate for being replaced with a macro in a future version of scalaz.
=> convenient syntax for repeated pattern matches

core/src/main/scala/scalaz/IList.scala, tests/src/test/scala/scalaz/FoldableTest.scala, tests/src/test/scala/scalaz/IListTest.scala, tests/src/test/scala/scalaz/std/ListTest.scala
Any ideas why this hasn't been caught by Travis in the [PR build](https://travis-ci.org/scalaz/scalaz/builds/376666222), but [was caught](https://travis-ci.org/scalaz/scalaz/builds/377230870) after merge?
=> Remove trailing whitespace.

effect/jvm/src/main/scala/scalaz/effect/RTS.scala, effect/jvm/src/test/scala/scalaz/effect/RTSTest.scala, effect/shared/src/main/scala/scalaz/effect/IO.scala
Implementation of `Stack` with always O(1) push/pop by avoiding array copy, using array nesting instead. Also has the nice property to "shrink" as the stack unroll.
Benchmarks show a 5% percent perf improvement, but I'd like someone else confirm this on a desktop because I do not trust by laptop cpu to yield continuous/consistent performance.
And also some other minor commits.
=> no array copy IO Stack

effect/src/main/scala/scalaz/effect/ST.scala
https://github.com/scala/scala/blob/15cc7fe354e4e7dc43246d7c78301940686bb4fc/src/library/scala/package.scala#L44-L47
deprecated since Scala 2.13
=> use Iterable instead of Traversable

LICENSE.txt, project/build.scala
update license year
Fixes scalaz/scalaz#1601
(I tried using `resources`, but that doesn't get included with the docs; this seems the easiest way to include some random file with no other meaning.)
=> add LICENSE.txt to all packaged jars.

core/src/main/scala/scalaz/IList.scala, core/src/main/scala/scalaz/NonEmptyList.scala
I've been doing some benchmarking and the varargs constructors (everywhere in the codebase) are a problem. It causes a `Seq` to be created, and then a further `List`.
There is not much we can do in 7.2, but for 7.3+ we should
- have explicit arity constructors
- (optionally) have a varargs after that
but there is arguably limited value in a varargs constructor anyway because of the performance hit.
Here I have added some binary compatible (and source equivalent) methods that should speed up a lot of codepaths. But I can't catch zero, 1 and 2 arguments because of source incompatible conflicts.
=> optimised IList / NonEmptyList constructors

base/shared/src/main/scala/scalaz/types/IsCovariantClass.scala, effect/shared/src/main/scala/scalaz/effect/IOInstances.scala, effect/shared/src/test/scala/scalaz/effect/CovariantResolutionTest.scala
Hello,
this a WIP attempt to resolve #1764. 
(Also, my first attempt to contribute to scalaz).
Is using `As.unsafeForce` the correct approach?
=> Add `IsCovariant` instance for `IO[E, ?]`. Fixes #1764

concurrent/src/main/scala/scalaz/concurrent/Task.scala, core/src/main/scala/scalaz/Cord.scala, core/src/main/scala/scalaz/DList.scala, core/src/main/scala/scalaz/Digit.scala, core/src/main/scala/scalaz/Heap.scala, core/src/main/scala/scalaz/IList.scala, core/src/main/scala/scalaz/NonEmptyList.scala, tests/jvm/src/test/scala/scalaz/std/FutureTest.scala, tests/src/test/scala/scalaz/IListTest.scala, tests/src/test/scala/scalaz/ZipperTest.scala
I wanted to do this in 7.2 but couldn't because of bincompat.
The `IList` and `NonEmptyList` constructors create intermediate `Seq` objects, and then all the foldLeft machinary inside the stdlib, which turns out is a huge bottleneck.
This creates convenient constructors for smaller arity, with a backcompat varargs after 6, at the cost of requiring people to call `.fromSeq` if they have a varargs value already.
I think it's a good tradeoff as it gives preferential treatment to people using scalazzi, and additional boilerplate for those who don't.
=> optimise {NonEmptyList, IList}.apply to avoid Seq construction

core/src/main/scala/scalaz/Inject.scala
It looks like the `Inject` typeclass has always been sealed (initial commit: https://github.com/scalaz/scalaz/commit/1d79ad50981db1a6931172d58baf5b341b223c87), but I've come across a use case where I'd like to define custom instances.
=> Expose Inject typeclass

CONTRIBUTING.md
Last part of #1305, this PR serves to discuss what guidelines to follow for the order of type parameters in classes to help with type inference.
=> Remove guideline for order of type parameters in classes

core/src/main/scala/scalaz/EitherT.scala, core/src/main/scala/scalaz/IndexedContsT.scala, core/src/main/scala/scalaz/Kleisli.scala, core/src/main/scala/scalaz/LazyOptionT.scala, core/src/main/scala/scalaz/MaybeT.scala, core/src/main/scala/scalaz/OptionT.scala, core/src/main/scala/scalaz/ReaderWriterStateT.scala, core/src/main/scala/scalaz/StateT.scala, core/src/main/scala/scalaz/Unapply.scala, core/src/main/scala/scalaz/UnwriterT.scala, core/src/main/scala/scalaz/WriterT.scala, core/src/main/scala/scalaz/package.scala, core/src/main/scala/scalaz/syntax/ContTOps.scala, core/src/main/scala/scalaz/syntax/KleisliOps.scala, effect/src/main/scala/scalaz/effect/LiftIO.scala, effect/src/main/scala/scalaz/effect/MonadIO.scala, example/src/main/scala/scalaz/example/ContTUsage.scala, example/src/main/scala/scalaz/example/ReaderWriterStateTUsage.scala, example/src/main/scala/scalaz/example/UnapplyInference.scala, example/src/main/scala/scalaz/example/transformers/typecheck/TypeCheckerWithExplicitTypes_MonadTransformers.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala, tests/src/test/scala/scalaz/EitherTTest.scala, tests/src/test/scala/scalaz/IndexedContsTTest.scala, tests/src/test/scala/scalaz/MonadErrorTest.scala, tests/src/test/scala/scalaz/ReaderWriterStateTTest.scala, tests/src/test/scala/scalaz/WriterTTest.scala
Addresses #1305 
Note:
- Did not do ReaderWriterStateT due to not knowing where the `F[_]` should go in the type signature (e.g. `RWST[R, F, W, S, A]` or `RWST[R, W, S, F, A]`? I'm assuming the latter...?)
- Not sure whether the swap for StateT and ContT are supposed to go deeper (e.g. also do swap in `IndexedStateT`)
- Some cases of using `StateT[S, F, A]` would not compile unless type was changed to that which it aliases: `IndexedStateT[F, S, S, A]`
- Not sure whether methods types or other classes should also be changed (e.g. `method[F[_], A]` stays the same? or becomes `method[A, F[_]]`? / `MonadPlus[F[_], A]` or `MonadPlus[A, F[_]]`)
- "Fix Later" commit: code wasn't compiling and I'm not sure how to fix it. Figured it'd be better to get more of this PR done and then figure that out …
=> Monad transformers switch type

base/shared/src/main/scala/scalaz/core/void.scala, base/shared/src/main/scala/scalaz/ct/choice.scala, base/shared/src/main/scala/scalaz/ct/iso.scala, base/shared/src/main/scala/scalaz/ct/kleisli.scala, base/shared/src/main/scala/scalaz/ct/strong.scala, base/shared/src/main/scala/scalaz/data/Cord.scala, base/shared/src/main/scala/scalaz/data/disjunction.scala, base/shared/src/main/scala/scalaz/data/these.scala, base/shared/src/main/scala/scalaz/package.scala, base/shared/src/main/scala/scalaz/prelude.scala, base/shared/src/main/scala/scalaz/types/as.scala, base/shared/src/main/scala/scalaz/types/is.scala, base/shared/src/main/scala/scalaz/types/leibniz.scala, base/shared/src/main/scala/scalaz/types/liskov.scala, effect/jvm/src/main/scala/scalaz/effect/RTS.scala, effect/jvm/src/main/scala/scalaz/effect/SafeApp.scala
I don't want to type `import scalaz._` and have trash like `Singleton`, `<:<`, `Array` just come popping out at me like that.
`StringContext` is evidently used by name so has to be kept here for `-Yno-imports`; I exported it `private[scalaz]` for laziness.
=> Remove some dubious re-exports from the scalaz package object.

core/src/main/scala-2.11/scalaz/compat.scala, core/src/main/scala-2.12/scalaz/compat.scala, core/src/main/scala-2.13/scalaz/compat.scala, core/src/main/scala/scalaz/Show.scala, project/build.scala, tests/src/test/scala/scalaz/SyntaxTest.scala
I don't know how to make this work with the test suite without setting up all the macro-based `shouldNotCompile` stuff, but it works.
Additionally, rename `show""` to `z""`, because I like it more. I'll be glad to take it out if other people don't like it, though.
cc @ChristopherDavenport
=> rename show"" -> z"", and use @implicitAmbiguous for more explanatory error messages

core/src/main/scala/scalaz/MonadError.scala, core/src/main/scala/scalaz/MonadListen.scala, core/src/main/scala/scalaz/MonadPlus.scala, core/src/main/scala/scalaz/MonadReader.scala, core/src/main/scala/scalaz/MonadState.scala, core/src/main/scala/scalaz/MonadTell.scala, example/src/main/scala/scalaz/example/FreeMonadsUsage.scala, tests/src/test/scala/scalaz/FreeTest.scala
Unless I am misunderstanding something, this seems to give us something like `Eff` out of the box for our MTL typeclasses.
It should be fairly easy to add something similar to `MonadError` and friends.
Thoughts?
If this is of interest, I could add some unit tests... I'm hoping people who review understand the concept, e.g. @edmundnoble 
Should these be `implicit`? They are creating coherent typeclasses, so could be. I'm willing to bet that it confuses the compiler more than helps.
=> Free Monads

core/src/main/scala/scalaz/Inject.scala
backport #1839 close #1839 
This is dependent on bincompat. :game_die: :game_die: :game_die:
=> Inject.instance

core/src/main/scala/scalaz/MonadError.scala, core/src/main/scala/scalaz/MonadListen.scala, core/src/main/scala/scalaz/MonadPlus.scala, core/src/main/scala/scalaz/MonadReader.scala, example/src/main/scala/scalaz/example/FreeMonadsUsage.scala
close #1887 ... it can't be done, Lord Tagless was right all along.
these encodings haven't been released yet, and even if they have been I doubt anybody is using them, so we should be fine to make this change.
=> revert self-referential Monad Asts

core/src/main/scala-2.12+/scalaz/ApplicativeParent.scala, core/src/main/scala/scalaz/Applicative.scala, core/src/main/scala/scalaz/Apply.scala, core/src/main/scala/scalaz/Isomorphism.scala, core/src/main/scala/scalaz/Validation.scala, core/src/main/scala/scalaz/package.scala, core/src/main/scala/scalaz/syntax/ApplicativeBuilder.scala, core/src/main/scala/scalaz/syntax/MonadErrorSyntax.scala, core/src/main/scala/scalaz/syntax/TraverseSyntax.scala, core/src/main/scala/scalaz/syntax/package.scala, example/src/main/scala/scalaz/example/ApplyUsage.scala
This PR does not add any features but instead makes it easier to use existing features.
Subject to binary compatibility, of course. In 7.3 we can apply the obvious changes to `Applicative` and if bincompat holds up, we can add `parApply` / `parTuple` to all the `ApplicativeBuilder`s.
I am particularly interested to hear @xuwei-k's thoughts on this! Seems we had similar ideas around `def parallel`, but I think we should delete `NonDeterminism`.
=> convenient methods and type aliases for parallelism

core/src/main/scala/scalaz/Maybe.scala, core/src/main/scala/scalaz/Order.scala
This PR is working in progress for issue #1885.
Accordingly with @fommil we decided to not implement an Alt[Maybe] instance in terms of class, as it was required.
That's because it would lead to ambiguity on implicit values.
=> instances: Decidable[Order], Alt[Maybe]

core/src/main/scala/scalaz/Alt.scala, core/src/main/scala/scalaz/Applicative.scala, core/src/main/scala/scalaz/Decidable.scala, core/src/main/scala/scalaz/Divisible.scala, core/src/main/scala/scalaz/InvariantAlt.scala, core/src/main/scala/scalaz/InvariantApplicative.scala, core/src/main/scala/scalaz/syntax/ApplicativeSyntax.scala, core/src/main/scala/scalaz/syntax/DivisibleSyntax.scala, core/src/main/scala/scalaz/syntax/InvariantAltSyntax.scala, core/src/main/scala/scalaz/syntax/InvariantApplicativeSyntax.scala, project/GenTypeClass.scala
Seems we've gone full circle... #1481 // @puffnfresh using an `Invariant` prefix naming convention (of the `Functor`, arguably arbitrarily) after discussing with Ed Kmett.
There is value in having this split from `InvariantAlt`, as it represents product and newtype derivation for lawful typeclasses, excluding coproducts.
=> Invariant parent of Applicative and Divisible

core/src/main/scala/scalaz/IStream.scala, core/src/main/scala/scalaz/OneAnd.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala, tests/src/test/scala/scalaz/IStreamTest.scala
A more flexible alternative to `EphemeralStream` that makes different implementation trade-offs. I'd appreciate feedback before I invest any more time into it. The by-name nature of `EphemeralStream` causes performance problems in `scalaz-deriving` where lazy semantics (not by-name) are very much preferred.
We could potentially change `EphemeralStream` to point here if we felt that the tradeoffs are strictly better.
One thing I don't like about this implementation, vs one where the head is always eager, is that a `OneAnd` with a lazy head will have a nested `Name[Name[A]]`. This suddenly becomes a usecase to reintroduce https://github.com/scalaz/scalaz/issues/1516 ... or to make `OneAnd` use `Name` for the head. I have the code sitting around somewhere.
@TomasMikula remember …
=> new data structure: IStream

core/src/main/scala/scalaz/MaybeT.scala, tests/src/test/scala/scalaz/MaybeTTest.scala
This is related to #1885 by @fommil .
I've implementeted `Decidable `instance for `MaybeT`.
I noticed that is possible to provide instances through `Decidable.fromIso`.
Anyway for `Decidable[MaybeT[F, ?]]` we require an instance of `Divisable[F]`.
Right now `Decidable.fromIso` requires an `implicit Decidable[F]`, so in this case we could have a problem. Any suggestion on this?
Furthermore, I could also refactor in this PR the provisioning of the other instances through `fromIso `as well if you prefer.
=> Decidable[MaybeT]

base/shared/src/main/scala/scalaz/data/ilist.scala, base/shared/src/main/scala/scalaz/tc/package.scala, base/shared/src/main/scala/scalaz/tc/unfoldable.scala, microsite/src/main/resources/microsite/data/menu.yml, microsite/src/main/tut/typeclass/Unfoldable.md
Related to https://github.com/scalaz/scalaz/pull/1917 and https://github.com/scalaz/scalaz-zio/pull/147.
Scalaz 7: #1626 
This PR will add `Unfoldable`, so that we can unfold data structure without `CanBuildFrom` machinery or similar.
```scala
trait UnfoldableClass[T[_]] {
def unfoldRight[A, B](f: B => Maybe2[A, B])(b: B): Maybe[T[A]]
def fromList[A](as: IList[A]): Maybe[T[A]] = unfoldRight(IList.uncons[A])(as)
}
```
=> Add Unfoldable

core/src/main/scala/scalaz/Either.scala, core/src/main/scala/scalaz/IList.scala, core/src/main/scala/scalaz/std/Either.scala, tests/src/test/scala/scalaz/IListTest.scala
close #1956 
Running this perf test
```scala
jsonformat/jmh:run -i 5 -wi 5 -f1 -t1 -w1 -r1 .*Geo.*decodeManual*
```
from https://gitlab.com/fommil/scalaz-deriving
BEFORE this change
```
Benchmark                               Mode  Cnt      Score     Error  Units
GeoJSONBenchmarks.decodeManualError    thrpt    5  25727.854 ± 263.755  ops/s
GeoJSONBenchmarks.decodeManualSuccess  thrpt    5  26943.126 ± 230.573  ops/s
```
AFTER this change
```
GeoJSONBenchmarks.decodeManualError    thrpt    5  70845.254 ± 890.444  ops/s
GeoJSONBenchmarks.decodeManualSuccess  thrpt    5  84736.783 ± 473.980  ops/s
```
and WITH custom short circution impl of traverseDisjunction from #1956 (which is used in the repo's master... back out that change to run the above tests)
``` …
```
=> Optimise Apply[{ Either, \/ }].apply2

README.md, example/src/main/scala/scalaz/example/ApplyUsage.scala, example/src/main/scala/scalaz/example/WordCount.scala, tests/jvm/src/test/scala/scalaz/concurrent/ConcurrentTest.scala
Fixing typos is sometimes very hard. It's not so easy to visually review them. Recently, I discovered a very useful tool for it, [misspell](https://github.com/client9/misspell). 
This pull request fixes minor typos detected by [misspell](https://github.com/client9/misspell) except for the false positives. If you would like me to work on other files as well, let me know. 
```
$ misspell . | grep -v '/js/'
README.md:149:83: "overriden" is a misspelling of "overridden"
example/src/main/scala/scalaz/example/ApplyUsage.scala:69:12: "refered" is a misspelling of "referred"
example/src/main/scala/scalaz/example/WordCount.scala:7:39: "Essense" is a misspelling of "Essence"
example/src/main/scala/scalaz/example/transformers/typecheck/TypeCheckerWithExplicitTypesAST.scala:16:26: "thn" is a …
```
=> Fix typos detected by github.com/client9/misspell

build.sbt
In order to keep the repo `scalaz.github.io` a little more organized, place the 7.x microsite in a folder.
=> Place microsite in folder

.jvmopts, .travis.yml, base/shared/src/main/scala/scalaz/data/acatenable1.scala, base/shared/src/main/scala/scalaz/data/biconst.scala, base/shared/src/main/scala/scalaz/data/const.scala, base/shared/src/main/scala/scalaz/data/package.scala, base/shared/src/main/scala/scalaz/tc/category.scala, base/shared/src/main/scala/scalaz/tc/semicategory.scala, base/shared/src/main/scala/scalaz/tc/semigroup.scala, tests/src/main/scala/scalaz/tests/ACatenable1Tests.scala, tests/src/main/scala/scalaz/tests/IListTests.scala, tests/src/main/scala/scalaz/tests/SMapTests.scala, tests/src/main/scala/scalaz/tests/TestMain.scala, tests/src/main/scala/scalaz/tests/z.scala
Also added a `Category[Function1]` (untested) and found a `Semicategory[Map]` (tested), added the `|+|` alias for `mappend`, the `<<<` and `>>>` aliases for `compose` and `andThen` respectively.
P.S.: Removed unnecessary indirection in `Const` instances.
P.P.S: Started running tests in parallel, just at the suite-level. Gives me almost a 2x speedup on my machine, 80 ms to 40 ms 😝
=> Tests for ACatenable1

base/shared/src/main/scala/scalaz/data/ilist.scala, base/shared/src/main/scala/scalaz/tc/package.scala, base/shared/src/main/scala/scalaz/tc/unfoldable.scala, base/shared/src/main/scala/scalaz/tc/unfoldable1.scala, microsite/src/main/resources/microsite/data/menu.yml, microsite/src/main/tut/typeclass/Unfoldable.md, microsite/src/main/tut/typeclass/Unfoldable1.md
This PR will:
- add Unfoldable1
- update Unfoldable, removing the annoying `Maybe` in the output of `unfoldRight`
The representation is now just like the one in [Purescript](https://pursuit.purescript.org/packages/purescript-unfoldable/3.0.0/docs/Data.Unfoldable) and #1626 (with a difference in the encoding).
I also updated the microsite, even if I think a resonable example may arise with `NonEmptyList`, which is still missing in Scalaz 8.
=> Add Unfoldable1, update Unfoldable

CONTRIBUTING.md, core/src/main/scala/scalaz/IList.scala, core/src/main/scala/scalaz/Maybe.scala
Previously:
```scala
def test(mi: Maybe[Int]) = mi match {
case Maybe.Just(_) => "J"
case Maybe.Empty() => "E"
}
```
would give a dead code warning on the `Empty` case, because Scala thinks that it will only match when `mi` could be a `Maybe[Nothing]`.
Closes scalaz/scalaz#1712.
=> Use hidden-covariance trick to avoid dead code warning.

base/shared/src/main/scala/scalaz/tc/applicative.scala, base/shared/src/main/scala/scalaz/tc/monoid.scala, build.sbt, tests/src/main/scala/scalaz/tests/IOTests.scala, tests/src/main/scala/scalaz/tests/TestMain.scala
Depending on a snapshot version of zio is unwise, since changes there can break us.
The `0.1-SNAPSHOT` release wasn't resolving at all.
This uses the 0.2.7 stable release, and updates `Applicative` and `Monoid`'s `Fiber` instances to use `Fiber` methods rather than directly subclassing `Fiber`.
Also, some tests for `IO`'s instances.
=> Use a stable ZIO release, update instances for it, rudimentary IO tests

benchmarks/src/main/scala/scalaz/tests/TestBenchmark.scala, build.sbt
If you'd like to benchmark the tests, this is a good way. We make sure to fork 5 JVMs and only actually run the benchmark once per iteration for realistic conditions (no JIT, classloading has to be redone on each iteration). The best way to use this is with async-profiler, as described at https://github.com/ktoso/sbt-jmh.
=> Benchmark tests

base/shared/src/main/scala/scalaz/data/io.scala, tests/src/main/scala/scalaz/tests/IOTests.scala, tests/src/main/scala/scalaz/tests/TestMain.scala
This PR is related to https://github.com/scalaz/scalaz/issues/1886.
Basically, it's just porting some convenience functions using scalaz adts (Either => \\/, Option => Maybe, etc..).
My remaining concerns are about:
- implementing `traverse`, `sequence`, `parTraverse` and `parAll` or not, since we may just use traversable syntax and get them for free
Thanks guys, coding under scalaz compiler restrictions is a really nice experience :)
=> Add convenience functions for IO

core/src/main/scala/scalaz/syntax/Syntax.scala
https://github.com/scalaz/scalaz/pull/2005 introduced ApplicativeError. In that change the ApplicativeError syntax was not added to ToTypeClassOps, see https://github.com/scalaz/scalaz/pull/2005/files#diff-64122d051e2ee46a48d1ff78860f997e.
=> Add ApplicativeError syntax to ToTypeClassOps

core/src/main/scala/scalaz/std/Vector.scala
(Goals as explained in #1022.)
For `Vector`, random access means we can treat the whole structure as a tree by just pivoting at the middle.  Stack consumption while traversing is logarithmic in vector length, but the implementation uses even less intermediate state, the trees are more balanced, and some obvious microoptimizations (see comment in code) can yield quick constant-factor improvements.
The pivot could be chosen a little more intelligently, e.g. a 4-6 split is more efficient than a 5-5 split when a `case 2` exists, but I have not done this, for simplicity.
I also believe a `DVector`-style approach, with `compose` in the inductive case, as with #1022's rolling, might pay off versus simply appending the vectors.  Again, simplicity has stayed my hand.
=> Top-down divide-and-conquer-style traverse for Vector.

core/src/main/scala/scalaz/Foldable.scala, tests/src/test/scala/scalaz/FoldableTest.scala
This uses only safe methods in Foldable.splitWith and Foldable.selectSplit without changing the logic.
I need this in order to perform migration to scalaz IList ( #2051 ) which does not have unsafe `tail` and `head` methods.
Also I think with explicit pattern matching - the implementation is cleaner. For example in `selectSplit`
there's no need to pass `boolean` in accumulator, to check for the previous state, since it is guaranteed by nonemptiness of the List.
=> safe methods in splitWith and selectSplit implementation#2051

core/src/main/scala/scalaz/PrioritySearchQueue.scala, tests/src/test/scala/scalaz/PrioritySearchQueueTest.scala
Priority queue that also supports lookup by key.
Implemented using `FingerTree`.
=> PrioritySearchQueue

example/src/main/scala/scalaz/example/AdjunctUsage.scala
I noticed a few mistakes when reading through the adjunct usage file.
=> Fix some spelling errors in Adjunct Usage

.gitignore, core/src/main/scala/scalaz/package.scala, tests/src/test/scala/scalaz/TagTest.scala
One of the most important use cases of tagged types is to define
alternative typeclass instances. But the fact that currently the
companion objects of the tag and the tagged type are not in the
implicit scope makes the whole feature very cumbersome to use.
We rectify the situation by adding implicit scope to tagged types.
=>  Make @@ abstract and add implicit scope to it 

core/src/main/scala/scalaz/EitherT.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala, tests/src/test/scala/scalaz/EitherTTest.scala
Since we can't have the bare `Applicative` instance for `EitherT`
due to potential inconsistencies, maybe we can have the
`Applicative.Par` instance?
=>  Applicative.Par instance for EitherT

build.sbt, project/build.scala
Stop polluting my oss folder. `show unmanagedSourceDirectories`:
```diff
[info] effectJVM / Compile / unmanagedSourceDirectories
[info] 	List(/Users/KrasteGe/work/oss/scalaz/scalaz/effect/jvm/src/main/scala, /Users/KrasteGe/work/oss/scalaz/scalaz/effect/jvm/src/main/scala-2.13, /Users/KrasteGe/work/oss/scalaz/scalaz/effect/jvm/src/main/scala-2, /Users/KrasteGe/work/oss/scalaz/scalaz/effect/jvm/src/main/java, /Users/KrasteGe/work/oss/scalaz/scalaz/effect/src/main/scala-2.13, /Users/KrasteGe/work/oss/scalaz/scalaz/effect/src/main/scala, /Users/KrasteGe/work/oss/scalaz/scalaz/effect/src/main/scala-2, /Users/KrasteGe/work/oss/scalaz/scalaz/effect/src/main/scala-2.13)
[info] scalacheckBindingJS / Compile / unmanagedSourceDirectories
[info] …
```
=> Fix unmanagedSourceDirectories settings

core/src/main/scala/scalaz/Heap.scala, tests/src/test/scala/scalaz/HeapTest.scala
Hello, 
I often use the Heap type in my projects and I am often used to do map/filter operations. To avoid 2 Heap runs I suggest you to add the very simple `collect` method.
=> Add collect method for Heap

core/src/main/scala/scalaz/Monad.scala
I explicitly define the return type F[B] of map function in Monad.
Please consider this.
Thank you.
=> add: return type of map function in Monad explicitly

core/src/main/scala/scalaz/Liskov.scala
https://github.com/scalaz/scalaz/commit/c65027c7ac7fafa86c7341badaebd2a7049d4de8
=> [7.2.x] move `Liskov.isa` method to LiskovInstances

core/src/main/scala/scalaz/Liskov.scala
https://github.com/scalaz/scalaz/commit/c65027c7ac7fafa86c7341badaebd2a7049d4de8
=> [7.3.x] move `Liskov.isa` method to LiskovInstances

build.sbt
The upstream issue that prevented it from working, https://github.com/scala-js/scala-js/issues/3953, was fixed in Scala.js 1.7.0.
=> Reenable StreamTTest in Scala.js.

core/src/main/scala/scalaz/StreamT.scala, tests/src/test/scala/scalaz/StreamTTest.scala
This PR adds the ReactiveX `flapMap` operator (named `mergeMap` in this PR), and the corresponding `StreamTMergeMonoid` instance
See 
http://reactivex.io/documentation/operators/flatmap.html
This PR is based on #2224
=> Add the StreamTMergeMonad instance (for #2223)

core/src/main/scala/scalaz/std/Future.scala
This PR cleans up the reference from the handler to the completed `Promise`, allowing the completed `Promise`, which might reference the whole execution, to be garbage-collected.
The handler itself is still a memory leak, however this is relatively mild.
See https://stackoverflow.com/a/36422958/955091 for the similar issue in `firstCompletedOf`
=> Reduce memory leaks due to choose

core/src/main/scala/scalaz/Cofree.scala
It is confusing when reading the `Cofree` about why `Free` is used here. This PR replaces it with `Free.Trampoline` for readability.
=> Replace `Free[Function0, *]` with `Free.Trampoline`

core/src/main/scala/scalaz/Coyoneda.scala
This PR allows using `Coyoneda[scala.collection.Future, *]` as a higher performance alternative to `Future`, especially when `map` and `bind` are called frequently, given that `Future.map` are more expensive than `Coyoneda.map`, e.g. `StreamT[Coyoneda[Future, *], A]` v.s. `StreamT[Future, A]`
=> Improve the performance of bind in subtypes of Bind[Coyoneda[F, *]]

core/src/main/scala/scalaz/StreamT.scala
This diff makes StreamT be a nonstrict SAM type, similar to `LazyList` and `EphemeralStream`, unlike the deprecated `Stream`.
=> Let StreamT be nonstrict

core/src/main/scala/scalaz/StreamT.scala, tests/src/test/scala/scalaz/StreamTTest.scala
It would be helpful for creating recursive `StreamT`s, otherwise it would create infinite `M.map` calls with `Skip` steps.
=> Add StreamT.noSkip and StreamT.noSkipRec

core/src/main/scala/scalaz/std/Future.scala, tests/jvm/src/test/scala/scalaz/std/FutureTest.scala
This PR implements `tailrecM` by running a tailrec loop instead of `flatMap` when `Future.value` is not `None`.
=> Add the BindRec instance for Future
