example/src/main/scala/scalaz/example/FreeCoyoUsage.scala
I have had this gist out there for a while and people seem to understand it, so here it is as a usage example.
=> example of free with coyoneda

core/src/main/scala/scalaz/ContravariantCoyoneda.scala, core/src/main/scala/scalaz/Coyoneda.scala
=> Remove CoyonedaF and ContravariantCoyonedaF

core/src/main/scala/scalaz/Unapply.scala
=> unapplyMFABCDE5 instance of Unapply

core/src/main/scala/scalaz/ListT.scala, tests/src/test/scala/scalaz/ListTTest.scala, tests/src/test/scala/scalaz/OptionTTest.scala
Inline with the behaviour of OptionT and MaybeT
=> Add listT to ListT

core/src/main/scala/scalaz/ISet.scala, core/src/main/scala/scalaz/ImmutableArray.scala, core/src/main/scala/scalaz/Map.scala, core/src/main/scala/scalaz/NonEmptyList.scala, core/src/main/scala/scalaz/Zipper.scala, core/src/main/scala/scalaz/std/Map.scala, core/src/main/scala/scalaz/std/Set.scala, core/src/main/scala/scalaz/std/Vector.scala, tests/src/test/scala/scalaz/FoldableTest.scala, tests/src/test/scala/scalaz/IListTest.scala, tests/src/test/scala/scalaz/ISetTest.scala, tests/src/test/scala/scalaz/ImmutableArrayTest.scala, tests/src/test/scala/scalaz/MapTest.scala, tests/src/test/scala/scalaz/NonEmptyListTest.scala, tests/src/test/scala/scalaz/ZipperTest.scala, tests/src/test/scala/scalaz/std/IterableTest.scala, tests/src/test/scala/scalaz/std/ListTest.scala, tests/src/test/scala/scalaz/std/MapTest.scala, tests/src/test/scala/scalaz/std/SetTest.scala, tests/src/test/scala/scalaz/std/VectorTest.scala
There are same issues mostly `Foldable` instances https://github.com/scalaz/scalaz/pull/796
=> more Foldable short circuiting

core/src/main/scala/scalaz/Bind.scala, core/src/main/scala/scalaz/syntax/BindSyntax.scala
`fproduct` like combinator on a Monad. If somebody can suggest better name, I'm open to suggestions :)
=> mproduct combinator in Bind

core/src/main/scala/scalaz/LazyOptionT.scala
The `orElse` methods on `OptionT`, `MaybeT`, `EitherT` and `LazyEitherT` all take transformers as their argument, so let's bring LazyOptionT in line with those.
=> Fix inconsistent LazyOptionT.orElse.

core/src/main/scala/scalaz/LazyEitherT.scala, core/src/main/scala/scalaz/LazyOption.scala, core/src/main/scala/scalaz/LazyOptionT.scala, core/src/main/scala/scalaz/MaybeT.scala, core/src/main/scala/scalaz/OptionT.scala
Squashed version of https://github.com/scalaz/scalaz/pull/939.
=> Add pipe syntax to Optional monads and transformers

core/src/main/scala/scalaz/ListT.scala, tests/src/test/scala/scalaz/ListTTest.scala
Implement find for ListT. I wonder why it is not included, if there are reasons, please feel free to just ignore this PR.
=> Add support for find on ListT

scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala
This is very similar to [my previous pull request](https://github.com/scalaz/scalaz/pull/943).
=> Remove another unnecessary covariance requirement

core/src/main/scala/scalaz/syntax/ApplySyntax.scala
=> Removing implicit Apply lifts

core/src/main/scala/scalaz/Either.scala, tests/src/test/scala/scalaz/DisjunctionTest.scala
=> Add Disjunction#recover and Disjunction#recoverWith

core/src/main/scala/scalaz/Divide.scala, core/src/main/scala/scalaz/Divisible.scala, core/src/main/scala/scalaz/Equal.scala, core/src/main/scala/scalaz/Order.scala, core/src/main/scala/scalaz/syntax/DivideSyntax.scala, core/src/main/scala/scalaz/syntax/DivisibleSyntax.scala, example/src/main/scala/scalaz/example/DivideExample.scala, project/GenTypeClass.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazProperties.scala
- https://github.com/ekmett/contravariant/blob/v1.3.2/src/Data/Functor/Contravariant/Divisible.hs
- https://youtu.be/cB8DapKQz-I?t=20m35s
- https://github.com/ekmett/contravariant/issues/18
- https://github.com/purescript/purescript-contravariant/pull/5
=> Divide and Divisible

core/src/main/scala/scalaz/OptionT.scala, tests/src/test/scala/scalaz/OptionTTest.scala
Transforms an OptionT[F,A] into a ListT[F,A]
=> Add toListT to OptionT

core/src/main/scala/scalaz/std/Either.scala, tests/src/test/scala/scalaz/std/EitherTest.scala
=> Implicit Show instance for Either[A,B]

core/src/main/scala/scalaz/OneAnd.scala
Good `F`s for `OneAnd` tend to have specialized `Foldable` functions; e.g. `Vector`'s `length` or `toVector`.  We can keep the improved performance of those specializations when lifting into `OneAnd` by dispatching to them directly with `OneAnd`'s own specializations.
=> Specialize various Foldable methods, and traverseS, for OneAnd.

core/src/main/scala/scalaz/Either.scala, tests/src/test/scala/scalaz/DisjunctionTest.scala
transform a \/[A,B] to an ValidationNel[A,B]
=> Add validationNel to Disjunction

core/src/main/scala/scalaz/Heap.scala, core/src/main/scala/scalaz/Tree.scala, core/src/main/scala/scalaz/TreeLoc.scala, core/src/main/scala/scalaz/std/Stream.scala, core/src/main/scala/scalaz/syntax/TreeOps.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala, tests/src/test/scala/scalaz/CofreeTest.scala, tests/src/test/scala/scalaz/TreeTest.scala
Clone of #1015, with the addition of removing uses of leaf and node throughout the rest of the project.
=> Make tree construction and pattern matching more consistent

core/src/main/scala/scalaz/NonEmptyList.scala, tests/src/test/scala/scalaz/NonEmptyListTest.scala
=> fix NonEmptyList.distinct to use its implicit Order

core/src/main/scala/scalaz/Map.scala, tests/src/test/scala/scalaz/MapTest.scala
This is a bit more in the FP spirit.
I updated all the tests, and they all pass.
=> Changed keySet from Set to ISet in ==>>

core/src/main/scala/scalaz/LazyEither.scala, core/src/main/scala/scalaz/LazyEitherT.scala, core/src/main/scala/scalaz/LazyOptionT.scala, tests/src/test/scala/scalaz/LazyEitherTTest.scala, tests/src/test/scala/scalaz/LazyEitherTest.scala, tests/src/test/scala/scalaz/LazyOptionTTest.scala, tests/src/test/scala/scalaz/LazyOptionTest.scala
=> added BindRec instances for LazyEither, LazyEitherT and LazyOptionT

core/src/main/scala/scalaz/EitherT.scala, tests/src/test/scala/scalaz/EitherTTest.scala
Fixes #1037  and adds a test for it as well.
=> Fix EitherT.orElse

core/src/main/scala/scalaz/Foldable.scala, core/src/main/scala/scalaz/Foldable1.scala, core/src/main/scala/scalaz/syntax/Foldable1Syntax.scala, core/src/main/scala/scalaz/syntax/FoldableSyntax.scala, tests/src/test/scala/scalaz/Foldable1Test.scala, tests/src/test/scala/scalaz/FoldableTest.scala
=> add [A:Order]distinct and [A:Equal]distinctE to Foldable/Foldable1

core/src/main/scala/scalaz/Foldable1.scala, core/src/main/scala/scalaz/syntax/Foldable1Syntax.scala, tests/src/test/scala/scalaz/NonEmptyListTest.scala
=> add Foldable1#{scanLeft1, scanRight1}

core/src/main/scala/scalaz/FreeT.scala, tests/src/test/scala/scalaz/FreeTTest.scala
https://github.com/paf31/purescript-freet/blob/v0.3.1/src/Control/Monad/Free/Trans.purs#L86-L97
=> FreeT hoist, interpret

core/src/main/scala/scalaz/Traverse.scala, core/src/main/scala/scalaz/syntax/TraverseSyntax.scala
To Traverse and Traverse's syntax.
=> Add generic zipWithIndex (called 'indexed')

.travis.yml, core/src/main/scala/scalaz/std/AllInstances.scala, core/src/main/scala/scalaz/std/java/time.scala, tests/src/test/scala/scalaz/std/java/TimeTest.scala
Let's start scalaz 7.3 development!
=> drop Java 7 support. add Java 8 time instances

core/src/main/scala/scalaz/Free.scala
=> use abstract type member in Free#Gosub

core/src/main/scala/scalaz/Free.scala, tests/src/test/scala/scalaz/FreeTest.scala
=> add Free#foldMapRec

core/src/main/scala/scalaz/Digit.scala, tests/src/test/scala/scalaz/DigitTest.scala
I found a typo in the digit append implementation.
I updated the test to test this case.
=> fix digit append

example/src/main/scala/scalaz/example/FreeApUsage.scala
Illustrates using FreeAp, example is a simple exercise in parsing meaningfully typed values out of a Map[String, Any]
=> FreeApUsage example

.travis.yml, project/build.scala
https://github.com/scala/make-release-notes/blob/9cfbdc8c92f94/experimental-backend.md#emitting-java-8-style-lambdas
=> update Scala 2.11.8, use Java8 Backend

core/src/main/scala/scalaz/FreeT.scala, tests/src/test/scala/scalaz/FreeTTest.scala
Most importantly on `map`. This is based off and depends on #1113.
=> Relax the S[_]: Functor constraint on some FreeT operations.

core/src/main/scala/scalaz/StreamT.scala, tests/src/test/scala/scalaz/StreamTTest.scala
`StreamT#foldRight` always evaluates the whole stream. This version is able to terminate early.
=> Add StreamT#foldRightM, which is able to terminate on an infinite stream.

concurrent/src/main/scala/scalaz/concurrent/PhasedLatch.scala, core/src/main/scala/scalaz/ApplicativePlus.scala, core/src/main/scala/scalaz/Bind.scala, core/src/main/scala/scalaz/CaseInsensitive.scala, core/src/main/scala/scalaz/Cord.scala, core/src/main/scala/scalaz/Enum.scala, core/src/main/scala/scalaz/FingerTree.scala, core/src/main/scala/scalaz/Kan.scala, core/src/main/scala/scalaz/Lens.scala, core/src/main/scala/scalaz/Memo.scala, core/src/main/scala/scalaz/Monad.scala, core/src/main/scala/scalaz/Name.scala, core/src/main/scala/scalaz/StateT.scala, core/src/main/scala/scalaz/Tree.scala, core/src/main/scala/scalaz/std/Tuple.scala, core/src/main/scala/scalaz/syntax/ApplicativeSyntax.scala, effect/src/main/scala/scalaz/effect/ST.scala, tests/jvm/src/test/scala/scalaz/NeedTestJVM.scala
=> Replacing lazy vals with `Need`

core/src/main/scala/scalaz/Profunctor.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazProperties.scala, tests/src/test/scala/scalaz/CoKleisliTest.scala, tests/src/test/scala/scalaz/KleisliTest.scala, tests/src/test/scala/scalaz/std/FunctionTest.scala
Thought we should have some laws.
=> Adding laws for profunctor

core/src/main/scala/scalaz/IndexedContsT.scala, tests/src/test/scala/scalaz/IndexedContsTTest.scala
As a by-product, this also tests Monad laws for `ContsT`, which don't seem to have been tested before.
=> MonadPlus instance for ContsT.

core/src/main/scala/scalaz/Free.scala, core/src/main/scala/scalaz/FreeT.scala, tests/src/test/scala/scalaz/FreeTTest.scala, tests/src/test/scala/scalaz/FreeTest.scala
This is a fix for #1156.
~~This PR is based off #1155 to avoid merge conflicts. In case that PR is deferred and this one good to go, I can rebase.~~
=> Ensure distinct Free/FreeT instances are not equal by ==.

core/src/main/scala/scalaz/StrictTree.scala, core/src/main/scala/scalaz/Tree.scala, core/src/main/scala/scalaz/syntax/StrictTreeOps.scala, core/src/main/scala/scalaz/syntax/Syntax.scala, example/src/main/scala/scalaz/example/MixedBag.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala, tests/jvm/src/test/scala/scalaz/StrictTreeTestJVM.scala, tests/jvm/src/test/scala/scalaz/TreeTestJVM.scala, tests/src/test/scala/scalaz/StrictTreeTest.scala
This is a strict version of Tree. Maybe some people would find it useful.
It's largely a copy of Tree, which I altered for maximum strictness.
=> add StrictTree

base/src/main/scala/BaseHierarchy.scala, base/src/main/scala/data/Const.scala, base/src/main/scala/data/ConstInstances.scala, base/src/main/scala/typeclass/Monoid.scala, base/src/main/scala/typeclass/MonoidClass.scala, base/src/main/scala/typeclass/MonoidInstances.scala, base/src/main/scala/typeclass/Semigroup.scala, base/src/main/scala/typeclass/SemigroupClass.scala, base/src/main/scala/typeclass/SemigroupInstances.scala, base/src/main/scala/typeclass/SemigroupSyntax.scala
This superseed https://github.com/scalaz/scalaz/pull/1190.
Just fixing a few stylish things but have to create this one to make jenkins and branch protection happy.
=> Add `Const` data type and the `Semigroup` and `Monoid` typeclasses.

CONTRIBUTING.md
Just added the two comments from @jbgi for now, there is plenty to add I'll try just to get the most important stuff and merge an initial version.
=> Add initial guidelines for contributing.

base/src/main/scala/data/DisjunctionFunctions.scala, base/src/main/scala/data/Lens.scala, base/src/main/scala/data/LensFunctions.scala, base/src/main/scala/data/Maybe.scala, base/src/main/scala/data/MaybeFunctions.scala, base/src/main/scala/data/MaybeOptics.scala, base/src/main/scala/data/Optic.scala, base/src/main/scala/data/OpticTypes.scala, base/src/main/scala/data/Prism.scala, base/src/main/scala/data/PrismFunctions.scala, base/src/main/scala/data/Traversal.scala, prelude/src/main/scala/Prelude.scala
Initial set of optics, to playground with optimization technics.
This PR target a topic branch, where the experimentation we'll happen until we settle on a design.
=> Initial optics

base/src/main/scala/typeclass/FoldableInstances.scala, base/src/main/scala/typeclass/TraversableInstances.scala
It's a rebased and squashed version of https://github.com/scalaz/scalaz/pull/1201 by @vmarquez.
=> Traversable consistency so it uses the TraversableClass.

base/src/main/scala/typeclass/TraversableFunctions.scala, base/src/main/scala/typeclass/TraversableSyntax.scala, prelude/src/main/scala/Prelude.scala
This is from https://github.com/scalaz/scalaz/pull/1209 just to trigger a new build.
=> Extract `TraversableFunctions`.

project/build.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalaCheckBinding.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazProperties.scala, tests/jvm/src/test/scala/scalaz/std/FutureTest.scala, tests/src/test/scala/scalaz/CoKleisliTest.scala, tests/src/test/scala/scalaz/CofreeTest.scala, tests/src/test/scala/scalaz/SpecLite.scala, tests/src/test/scala/scalaz/StoreTTest.scala, tests/src/test/scala/scalaz/UnwriterTTest.scala, tests/src/test/scala/scalaz/WriterTTest.scala, tests/src/test/scala/scalaz/std/FunctionTest.scala, tests/src/test/scala/scalaz/std/MapTest.scala, tests/src/test/scala/scalaz/std/StreamTest.scala
=> scalacheck 1.13.1

core/src/main/scala/scalaz/MonadTrans.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazProperties.scala, tests/src/test/scala/scalaz/CodensityTest.scala, tests/src/test/scala/scalaz/EitherTTest.scala, tests/src/test/scala/scalaz/FreeTTest.scala, tests/src/test/scala/scalaz/KleisliTest.scala, tests/src/test/scala/scalaz/ListTTest.scala, tests/src/test/scala/scalaz/MaybeTTest.scala, tests/src/test/scala/scalaz/ReaderWriterStateTTest.scala, tests/src/test/scala/scalaz/StateTTest.scala, tests/src/test/scala/scalaz/TheseTTest.scala, tests/src/test/scala/scalaz/WriterTTest.scala
From [Monad transformer (Wikipedia)](https://en.wikipedia.org/wiki/Monad_transformer):
```haskell
lift . return = return
lift (m `bind` k) = (lift m) `bind` (lift . k)
```
=> Add monad transformer laws.

build.sbt, project/build.properties, project/build.scala
- https://github.com/sbt/sbt/commit/f2f12022a5672c3f57b8e5fce4227da455ab8024
- https://github.com/sbt/sbt/blob/v0.13.12/main/src/main/scala/sbt/Build.scala#L11
=> sbt 0.13.12. use build.sbt

example/src/main/scala/scalaz/example/CodensityUsage.scala
There is a problem in this example: you can yield closed resource. But solving this problem is not in scope of this example :)
=> Example of using Codensity for resource management

core/src/main/scala/scalaz/Injective.scala, core/src/main/scala/scalaz/std/Either.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala, tests/src/test/scala/scalaz/std/EitherTest.scala
https://github.com/scala/scala/commit/6e9faf5157132ad575c98e5a9a0919ac38b7beb8
=> remove RightProjection/LeftProjection instances

CONTRIBUTING.md, base/src/main/scala/data/Maybe.scala, base/src/main/scala/data/MaybeFunctions.scala, base/src/main/scala/typeclass/Contravariant.scala, base/src/main/scala/typeclass/Liskov.scala, base/src/main/scala/typeclass/LiskovFunctions.scala, base/src/main/scala/typeclass/LiskovInstances.scala, base/src/main/scala/typeclass/LiskovTypes.scala
Following an original idea from @S11001001 (http://typelevel.org/blog/2014/03/09/liskov_lifting.html) and suggestion made by @puffnfresh on the mailing list (which I do discover I was not subscribed to since.... quite a while).
I'm convinced `Liskov.liftCvf` will be useful in other situation, Stephen gave me some ideas about it :)
=> Liskov lift dat shit.

concurrent/src/main/scala/scalaz/concurrent/Task.scala
Previously we were overriding gatherUnordered which was not actually
called when Task.gatherUnordered was called with its default argument.
Instead chooseAny was being called, which gave very poor performance:
```scala
val start = System.currentTimeMillis
Task.gatherUnordered((1 to 1000).map(Task.now)).unsafePerformSync
println(System.currentTimeMillis - start)
```
For me, the above code before this change gives 563ms.
After this change gives 2ms.
This also makes the underlying Task code consistent with Future. When we
call Task.gatherUnordered, we're now pretty much calling the equivalent
of Future.gatherUnordered.
We should also figure out why Future's chooseAny is very slow, or if
chooseAny is even useful.
=> Override reduceUnordered in Task's Nondeterminism

core/src/main/scala/scalaz/Maybe.scala, core/src/main/scala/scalaz/std/Option.scala, core/src/main/scala/scalaz/syntax/std/OptionOps.scala
=> Add getOrElseF function to Option and Maybe.

base/src/main/scala/typeclass/MonoidInstances.scala
=> Fix missing package from MonoidInstances

core/src/main/scala/scalaz/Const.scala, tests/src/test/scala/scalaz/ConstTest.scala
https://github.com/ekmett/contravariant/commit/9392aeefa69d55469b04d3870df44d5bac6f079e
=> add Divide[Const], Divisible[Const]

core/src/main/scala/scalaz/Free.scala
=> Fix value discarding in Free.produce

core/src/main/scala/scalaz/MonadState.scala, tests/src/test/scala/scalaz/FreeTTest.scala, tests/src/test/scala/scalaz/StateTTest.scala
Also added @xuwei-k's case to tests.
=> Revert implicit promotedMonadState. Fixes #1308.

LICENSE.txt
https://help.github.com/articles/licensing-a-repository/
=> move LICENSE file for GitHub gives special treatment

example/src/main/scala/scalaz/example/TagUsage.scala
=> Doc: Tags only never box for AnyRef underlying values

project/build.scala
- https://twitter.com/jb9i/status/838401563504820225
- https://github.com/scala-native/scala-native/issues/562
- https://github.com/scala/community-builds/issues/500
/cc @SethTisue @densh @MasseGuillaume @jbgi
=> workaround for https://github.com/scala-native/scala-native/issues/562

core/src/main/scala/scalaz/EphemeralStream.scala, tests/jvm/src/test/scala/scalaz/EphemeralStreamTestJVM.scala
Rebased/squashed version of #1104 with the change mentioned in https://github.com/scalaz/scalaz/pull/1104#issuecomment-292121444
=> Improve EphemeralStream's weakMemo to be optimistic through CAS (Rebased)

core/src/main/scala/scalaz/Memo.scala
=> Deprecate Memo.weakHashMapMemo

core/src/main/scala/scalaz/std/List.scala, core/src/main/scala/scalaz/std/Map.scala, core/src/main/scala/scalaz/std/SortedMap.scala, core/src/main/scala/scalaz/std/Stream.scala, core/src/main/scala/scalaz/std/Vector.scala
... to avoid mapping over the collection.
=> Override Functor#widen for covariant std collections

core/src/main/scala/scalaz/FreeT.scala
Analogous to the same method added on `Free` in #1365.
=> Add method FreeT#resumeC, a variant of resume that doesn't require Functor

README.md
=> Mention IRC channel, google group in README

core/src/main/scala/scalaz/ISet.scala, core/src/main/scala/scalaz/std/Set.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazProperties.scala, tests/src/test/scala/scalaz/ISetTest.scala, tests/src/test/scala/scalaz/std/SetTest.scala
ref https://github.com/scalaz/scalaz/issues/1379
=> add ScalazProperties.band and Set instances

core/src/main/scala/scalaz/Semigroup.scala, tests/src/test/scala/scalaz/BandTest.scala
https://github.com/scalaz/scalaz/issues/1379
=> add some Band instances

core/src/main/scala/scalaz/Maybe.scala, core/src/main/scala/scalaz/std/Option.scala, tests/src/test/scala/scalaz/MaybeTests.scala, tests/src/test/scala/scalaz/std/OptionTest.scala
https://github.com/scalaz/scalaz/issues/1379
=> Band instances for Option and Maybe

core/src/main/scala/scalaz/std/AnyVal.scala, tests/src/test/scala/scalaz/std/AnyValTest.scala
https://github.com/scalaz/scalaz/issues/1379
=> Band instances for Boolean

base/src/main/scala/Prelude.scala, base/src/main/scala/typeclass/InvariantFunctor.scala, base/src/main/scala/typeclass/InvariantFunctorClass.scala, base/src/main/scala/typeclass/InvariantFunctorFunctions.scala, base/src/main/scala/typeclass/InvariantFunctorSyntax.scala
=> invariant functor

base/src/main/scala/data/Forget.scala, base/src/main/scala/data/ForgetInstances.scala
Just thought I'd get my feet wet with trying to understand where everything goes.  We also may not want/need this depending...
=> Forget structure

base/shared/src/main/scala/scalaz/Prelude.scala, base/shared/src/main/scala/scalaz/data/MaybeFunctions.scala, base/shared/src/main/scala/scalaz/data/MaybeInstances.scala, base/shared/src/main/scala/scalaz/typeclass/IsContravariant.scala, base/shared/src/main/scala/scalaz/typeclass/IsContravariantClass.scala, base/shared/src/main/scala/scalaz/typeclass/IsContravariantInstances.scala, base/shared/src/main/scala/scalaz/typeclass/IsCovariant.scala, base/shared/src/main/scala/scalaz/typeclass/IsCovariantClass.scala, base/shared/src/main/scala/scalaz/typeclass/IsCovariantInstances.scala, base/shared/src/main/scala/scalaz/typeclass/Liskov.scala, base/shared/src/main/scala/scalaz/typeclass/LiskovFunctions.scala, base/shared/src/main/scala/scalaz/typeclass/LiskovInstances.scala
=> IsCovariant, IsContravariant.

.travis.yml, base/shared/src/main/scala/scalaz/data/ACatenable1.scala, base/shared/src/main/scala/scalaz/data/AList.scala, sbt
=>  Take advantage of tail-recursive calls with varying type arguments.

.travis.yml, base/shared/src/main/scala/scalaz/data/Forall.scala, base/shared/src/main/scala/scalaz/data/Forall2.scala, project/ScalazBuild.scala, sbt
Taking advantage of scala/scala#6069
=>  Enable -Xsource:2.13 and resolve subsequent ambiguous implicits

core/src/main/scala/scalaz/Show.scala, core/src/main/scala/scalaz/syntax/ShowSyntax.scala, tests/src/test/scala/scalaz/SyntaxTest.scala
Having difficulty with the final materialization for sealed traits, as it doesn't find the Show.Shows, which I think it should. 
It's probably something very simple.
Otherwise works as expected.
=> Add Show Interpolator

core/src/main/scala/scalaz/IList.scala, core/src/main/scala/scalaz/syntax/EqualSyntax.scala
as per the duelling banjos at https://github.com/fosskers/scalaz-and-cats/pull/4
=> Faster IListEquals

example/src/main/resources/microsite/data/menu.yml, example/src/main/tut/typeclass/Semigroup.md
=> [8.0.x] example: Add Semigroup

example/src/main/resources/microsite/data/menu.yml, example/src/main/tut/typeclass/Monoid.md
=> [8.0.x] example: Add Monoid

core/src/main/scala/scalaz/OneAnd.scala
originally in the abandoned #1569
=> fix the OneAnd isomorphism

core/src/main/scala/scalaz/syntax/BindSyntax.scala, core/src/main/scala/scalaz/syntax/FunctorSyntax.scala
=> avoid a method hop when using liskov

core/src/main/scala/scalaz/ISet.scala
this seems too obvious... so I'm wondering if there is something subtle why we're not doing this already.
=> ISet.insert optimisation

core/src/main/scala/scalaz/Maybe.scala
=> Maybe.orEmpty takes ApplicativePlus, not Applicative + PlusEmpty

core/src/main/scala/scalaz/EitherT.scala, core/src/main/scala/scalaz/syntax/EitherTOps.scala, core/src/main/scala/scalaz/syntax/Syntax.scala, tests/src/test/scala/scalaz/EitherTTest.scala
forward port of #1561
// @xuwei-k are you ok with this breaking change?
=> some convenient constructors for EitherT (#1561)

core/src/main/scala/scalaz/std/AllInstances.scala, core/src/main/scala/scalaz/std/String.scala, core/src/main/scala/scalaz/std/java/math/BigDecimal.scala, core/src/main/scala/scalaz/syntax/std/StringOps.scala, tests/src/test/scala/scalaz/std/StringTest.scala
=> Add safe parsing without exceptions

effect/src/main/scala/scalaz/effect/IORef.scala, effect/src/main/scala/scalaz/effect/ST.scala
=> Remove implicit conversion from ST to IO

example/src/main/resources/microsite/data/menu.yml, example/src/main/tut/typeclass/Monad.md
=> [8.0.x] example: Add Monad

core/src/main/scala/scalaz/FingerTree.scala
a far cry from #1609 this at least hides some of the types in the companion, away from the `scalaz` namespace.
=> move internal ADT details into the FingerTree companion

core/src/main/scala/scalaz/Tannen.scala
Composes a Functor on the outside of a Bifunctor.
=> Add Tannen

core/src/main/scala/scalaz/ImmutableArray.scala, core/src/main/scala/scalaz/Memo.scala, tests/src/test/scala/scalaz/MemoTest.scala
deprecations as removed in #1597 and #1598
=> mark deprecations

core/src/main/scala/scalaz/Digit.scala, tests/src/test/scala/scalaz/DigitTest.scala
also use direct array lookup to speedup some existing Digit methods.
=> Add digitsFrom{Int, Long, BigInt}: extract digits of a number,

core/src/main/scala/scalaz/WriterT.scala, project/build.scala, tests/src/test/scala/scalaz/FreeTTest.scala
https://github.com/scalaz/scalaz/issues/1629
=> remove "-Xsource:2.12" option if Scala 2.13. fix errors

CONTRIBUTING.md
Aims to address #1631. I would not consider this PR as ready to merge just yet, but it is open for feedback. @jdegoes, @joroKr21, please let me know what else we can add to this? I am a bit stuck on how we can check for binary compatibility. Are there any good out-of-the-box tools we can use to check for binary compatibility?
=> Adding on steps to build and test Scalaz locally. (Issue #1631)

core/src/main/scala/scalaz/WriterT.scala
=> optimise WriterT's listen

core/src/main/scala/scalaz/Foldable.scala, core/src/main/scala/scalaz/Foldable1.scala, core/src/main/scala/scalaz/IList.scala, core/src/main/scala/scalaz/NonEmptyList.scala, core/src/main/scala/scalaz/std/List.scala, core/src/main/scala/scalaz/syntax/Foldable1Syntax.scala, core/src/main/scala/scalaz/syntax/FoldableSyntax.scala, tests/src/test/scala/scalaz/FoldableTest.scala, tests/src/test/scala/scalaz/IListTest.scala, tests/src/test/scala/scalaz/NonEmptyListTest.scala, tests/src/test/scala/scalaz/std/ListTest.scala
close #1672 
I'd like to have `asum1` and `atraverse1` variants as well.
=> asum and asumMap

project/build.scala
=> enable scalac optimisations

core/src/main/scala/scalaz/Kleisli.scala, tests/src/test/scala/scalaz/MonadErrorTest.scala
`String` was being used for two different things, this clears up the intent.
=> clearer MonadErrorTest

base/shared/src/main/scala/scalaz/Prelude.scala, base/shared/src/main/scala/scalaz/data/Iso.scala, base/shared/src/main/scala/scalaz/data/Void.scala, base/shared/src/main/scala/scalaz/data/package.scala
https://github.com/scalaz/scalaz/pull/1698#issuecomment-379895959
=> Better Void.

example/src/main/resources/microsite/data/menu.yml, example/src/main/tut/data/Kleisli.md
Addresses @NeQuissimus' post-merge comments [here](https://github.com/scalaz/scalaz/pull/1741)
=> Fix Kleisli Documentation

effect/jvm/src/main/scala/scalaz/effect/RTS.scala, effect/jvm/src/test/scala/scalaz/effect/RTSTest.scala, effect/shared/src/main/scala/scalaz/effect/ExitResult.scala, effect/shared/src/main/scala/scalaz/effect/IO.scala, effect/shared/src/main/scala/scalaz/effect/Promise.scala
Fixes [this](https://github.com/scalaz/ioeffect/issues/30) and cleans up code considerably.
=> Scalaz8 cleanup

base/shared/src/main/scala/scalaz/typeclass/DebugSyntax.scala, example/src/main/tut/typeclass/Debug.md
=> Add string interpolator for Debug

effect/src/main/scala/scalaz/effect/ST.scala, tests/src/test/scala/scalaz/effect/STTest.scala
=> fix STArray#fill

core/src/main/scala/scalaz/NaturalTransformation.scala, core/src/main/scala/scalaz/package.scala
Guess who has been doing a lot of natural transformations recently...
I'm surprised that these don't exist already, so maybe I just couldn't find them.
I called these `hoist` because of the similarity to `Hoist.hoist` but without requiring a `Monad`.
=> NaturalTransformation.liftMap and State.hoist

base/shared/src/main/scala/scalaz/data/Void.scala, base/shared/src/main/scala/scalaz/typeclass/EqInstances.scala
=> Add semigroup instance for Void  #1777

effect/jvm/src/test/scala/scalaz/effect/IOInstancesSpec.scala, effect/shared/src/main/scala/scalaz/effect/IOInstances.scala
=> Add Bifunctor instance for IO

effect/README.md, effect/jvm/src/main/scala/scalaz/effect/RTS.scala, effect/jvm/src/main/scala/scalaz/effect/SafeApp.scala
=> Modify `SafeApp#run` to return `IO[Void, ExitStatus]`

core/src/main/scala/scalaz/package.scala
I found this to be pretty useful but also quite fiddly to create, hence useful for `core`.
Courtesy of @alexknvl who wrote the initial draft.
It will conflict with #1765 but I can fix that easily.
=> State.united

effect/jvm/src/test/scala/scalaz/effect/generator/GenIO.scala
=> Introduce GenIO trait (GenIO.scala) with generators for IO

.travis.yml, build.sbt
No way to know whether this works until we merge -.-
The Travis CLI decided to re-format the `.travis.yml`, I hope nobody was married to the old formatting...
Follow-up to #1742
=> Fix Sonatype credentials

effect/jvm/src/main/scala/scalaz/effect/RTS.scala, effect/shared/src/main/scala/scalaz/effect/Async.scala, effect/shared/src/main/scala/scalaz/effect/package.scala
Addresses this https://github.com/scalaz/scalaz/issues/1786
=> Issue 1786 - Improve Async in Scalaz 8 IO

.travis.yml, project/build.scala, project/plugins.sbt
use same credentials of 8.0.x https://github.com/scalaz/scalaz/commit/547c026dd7abee2f4749975d18d10ac83109827c
=> [7.3.x] add release SNAPSHOT setting

build.sbt, project/ScalazBuild.scala
=> silencer: 0.6 -> 1.0, kind-projector: 0.9.6 -> 0.9.7

core/src/main/scala/scalaz/Bitraverse.scala, core/src/main/scala/scalaz/Kleisli.scala, core/src/main/scala/scalaz/NullResult.scala, core/src/main/scala/scalaz/ReaderWriterStateT.scala, core/src/main/scala/scalaz/StateT.scala, core/src/main/scala/scalaz/Traverse.scala, core/src/main/scala/scalaz/package.scala, core/src/main/scala/scalaz/std/List.scala, core/src/main/scala/scalaz/std/Vector.scala, core/src/main/scala/scalaz/syntax/StateOps.scala, effect/src/main/scala/scalaz/effect/LiftIO.scala, effect/src/main/scala/scalaz/effect/MonadIO.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala, tests/src/test/scala/scalaz/StateTTest.scala
Continuation of #1800 so that that PR can be merged while the problems with StateT get figured out.
=> Swap StateT type parameters

example/src/main/tut/ct/Applicative.md, example/src/main/tut/ct/Monad.md
It misled someone on Gitter and is a bad bad example for the children.
=> Don't provide the ZipList applicative instance for List in the docs.

base/shared/src/main/scala/scalaz/basehierarchy.scala, base/shared/src/main/scala/scalaz/ct/contravariant.scala, base/shared/src/main/scala/scalaz/ct/functor.scala, base/shared/src/main/scala/scalaz/ct/phantom.scala
=> Make Contravariant a subclass of InvariantFunctor

project/build.scala
"-Ywarn-unused-import" deleted since Scala 2.13
https://github.com/scala/scala/commit/ad25805de5c63084348348aabefdf184927806c2
=> fix -Ywarn-unused scalacOptions

base/shared/src/main/scala/scalaz/data/these.scala, example/src/main/tut/data/These.md
See https://github.com/scalaz/scalaz/pull/1833 for information on why this is better.
=> Fix type inference on These#fold

README.md
IRC, Discord, and Gitter.
~For this @emilypi or @edmundnoble or some discord admin needs to turn on the widget.~ thx based mle
~Also, the discord invite link says "haro has invited you to join scalaz". I don't know if there's a way to make it not mention me. If not, I should make my discord image match my github one.~
[It looks like this](https://github.com/hrhino/scalaz/tree/topic/chats).
=> add chat badges to readme

base/shared/src/main/scala/scalaz/ct/kleisli.scala, base/shared/src/main/scala/scalaz/data/ilist.scala, base/shared/src/main/scala/scalaz/prelude.scala, microsite/src/main/tut/ct/Kleisli.md
Sup folks, here's a basic API for `IList`
=> Missing IList API

core/src/main/scala/scalaz/IdT.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala, tests/src/test/scala/scalaz/IdTTest.scala
This PR is related to #1885 by @fommil .
- Decidable and Divisable instances for IdT.
- Unit tests for Decidable and Divisable.
=> [WIP] Decidable[IdT] and Divisible[IdT]

core/src/main/scala/scalaz/Traverse.scala, core/src/main/scala/scalaz/syntax/TraverseSyntax.scala, tests/src/test/scala/scalaz/TraverseTest.scala
sequenceM for Traverse.
There is no issue related to it, but it was mentioned on Gitter.
=> sequenceM for Traverse

build.sbt, project/plugins.sbt
This adds a link in the top right corner that points to the Scaladoc
=> Add Scaladoc link to microsite

site/src/main/resources/microsite/layouts/scalaz.html, site/src/main/tut/data/Disjunction.md, site/src/main/tut/data/index.md, site/src/main/tut/index.md, site/src/main/tut/std/List.md, site/src/main/tut/std/index.md, site/src/main/tut/typeclass/Equal.md, site/src/main/tut/typeclass/index.md
Adds a link to each page labelled "[edit]", which redirects to an edit on GitHub.
@fommil with the great ideas again :+1:
=> Add [edit] links to all pages

core/src/main/scala/scalaz/APair.scala, core/src/main/scala/scalaz/Exists.scala, core/src/main/scala/scalaz/IStream.scala, core/src/main/scala/scalaz/Maybe.scala, core/src/main/scala/scalaz/package.scala, example/src/main/scala/scalaz/example/MixedBag.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazProperties.scala
typical. I find some typos when the horses are let out of the stable.
=> IStream.headMaybe, Just.get, APair, Pair

core/src/main/scala/scalaz/Maybe.scala, tests/src/test/scala/scalaz/MaybeTests.scala
@tonymorris 
suspected use case demolished
=> undo method on subtype

base/shared/src/main/scala/scalaz/core/io.scala
Not sure of the wisdom of depending on a snapshot.
=> Fix build after scalaz-zio changes.

core/src/main/scala/scalaz/EphemeralStream.scala, core/src/main/scala/scalaz/IList.scala, core/src/main/scala/scalaz/NonEmptyList.scala, core/src/main/scala/scalaz/Reducer.scala, core/src/main/scala/scalaz/std/Stream.scala, tests/src/test/scala/scalaz/TraverseTest.scala
For [issue #1716](https://github.com/scalaz/scalaz/issues/1716#issuecomment-388029722)
=> Make Traversables short-circuiting and stack-safe

base/shared/src/main/scala/scalaz/tc/applicative.scala, base/shared/src/main/scala/scalaz/tc/monoid.scala
Once again, this will make it compile again :)
Related #1931
=> Align with latest updates in zio

core/src/main/scala/scalaz/Applicative.scala, core/src/main/scala/scalaz/Apply.scala, core/src/main/scala/scalaz/Catchable.scala, core/src/main/scala/scalaz/Either.scala, core/src/main/scala/scalaz/EitherT.scala, core/src/main/scala/scalaz/IList.scala, core/src/main/scala/scalaz/Inject.scala, core/src/main/scala/scalaz/Kleisli.scala, core/src/main/scala/scalaz/Maybe.scala, core/src/main/scala/scalaz/MonadState.scala, core/src/main/scala/scalaz/MonadTell.scala, core/src/main/scala/scalaz/Validation.scala, core/src/main/scala/scalaz/package.scala, core/src/main/scala/scalaz/std/Either.scala, core/src/main/scala/scalaz/syntax/ApplicativeBuilder.scala, core/src/main/scala/scalaz/syntax/MonadErrorSyntax.scala, core/src/main/scala/scalaz/syntax/TraverseSyntax.scala, example/src/main/scala/scalaz/example/ApplyUsage.scala, example/src/main/scala/scalaz/example/FreeMonadsUsage.scala, project/GenTypeClass.scala, tests/src/test/scala/scalaz/DisjunctionTest.scala, tests/src/test/scala/scalaz/IListTest.scala, tests/src/test/scala/scalaz/MaybeTests.scala, tests/src/test/scala/scalaz/MonadErrorTest.scala
These commits didn't cherry pick cleanly from 7.2 onto 7.3, so I had to go through each of them manually and reapply them. // @xuwei-k thank you for automatically cherry picking the ones that were clean!
Since these things have already been reviewed, I'll merge when green.
=> Forward port several improvements to series/7.2.x

core/src/main/scala/scalaz/Kleisli.scala, core/src/main/scala/scalaz/ListT.scala, core/src/main/scala/scalaz/OptionT.scala, core/src/main/scala/scalaz/StateT.scala, core/src/main/scala/scalaz/WriterT.scala, tests/src/test/scala/scalaz/KleisliTest.scala, tests/src/test/scala/scalaz/ListTTest.scala, tests/src/test/scala/scalaz/OptionTTest.scala, tests/src/test/scala/scalaz/StateTTest.scala, tests/src/test/scala/scalaz/WriterTTest.scala
This is related to #1885 by @fommil .
=> Add more decidable/divisible instances

build.sbt, tests/src/main/scala/scalaz/tests/AFixTests.scala, tests/src/main/scala/scalaz/tests/TestMain.scala
`tests/run show` output:
https://gist.github.com/edmundnoble/412f457a5a607191733b15f895ab095e
=> AFix tests, testz update, `show` option

base/shared/src/main/scala/scalaz/data/acatenable1.scala, base/shared/src/main/scala/scalaz/data/alist.scala, base/shared/src/main/scala/scalaz/data/alist1.scala, base/shared/src/main/scala/scalaz/data/balanced.scala, base/shared/src/main/scala/scalaz/data/biconst.scala, base/shared/src/main/scala/scalaz/data/forall3.scala, base/shared/src/main/scala/scalaz/data/package.scala, project/build.properties, tests/src/main/scala/scalaz/tests/ACatenable1Tests.scala, tests/src/main/scala/scalaz/tests/AList1Tests.scala, tests/src/main/scala/scalaz/tests/TestMain.scala
=> Alist1 tests

base/shared/src/main/scala/scalaz/data/amaybe.scala, base/shared/src/main/scala/scalaz/data/amaybe2.scala, base/shared/src/main/scala/scalaz/tc/debug.scala, base/shared/src/main/scala/scalaz/tc/unfoldable1.scala, build.sbt, microsite/src/main/tut/data/Maybe2.md, tests/src/main/scala/scalaz/tests/ACatenable1Tests.scala, tests/src/main/scala/scalaz/tests/AFixTests.scala, tests/src/main/scala/scalaz/tests/AList1Tests.scala, tests/src/main/scala/scalaz/tests/AMaybe2Tests.scala, tests/src/main/scala/scalaz/tests/AMaybeTests.scala, tests/src/main/scala/scalaz/tests/DebugInterpolatorTest.scala, tests/src/main/scala/scalaz/tests/DoubleTests.scala, tests/src/main/scala/scalaz/tests/IListTests.scala, tests/src/main/scala/scalaz/tests/SMapTests.scala, tests/src/main/scala/scalaz/tests/TestMain.scala, tests/src/main/scala/scalaz/tests/z.scala
Depends on #1971, updates us to 0.0.5, allowing us to delete some redundant crap.
=> Testz 0.0.5

base/shared/src/main/scala/scalaz/data/acatenable1.scala, base/shared/src/main/scala/scalaz/data/alist.scala, base/shared/src/main/scala/scalaz/data/alist1.scala, base/shared/src/main/scala/scalaz/data/amaybe.scala, base/shared/src/main/scala/scalaz/data/amaybe2.scala, base/shared/src/main/scala/scalaz/data/biconst.scala, base/shared/src/main/scala/scalaz/data/forall3.scala, base/shared/src/main/scala/scalaz/data/package.scala, base/shared/src/main/scala/scalaz/tc/debug.scala, base/shared/src/main/scala/scalaz/tc/unfoldable1.scala, build.sbt, microsite/src/main/tut/data/Maybe2.md, tests/src/main/scala/scalaz/tests/ACatenable1Tests.scala, tests/src/main/scala/scalaz/tests/AFixTests.scala, tests/src/main/scala/scalaz/tests/AList1Tests.scala, tests/src/main/scala/scalaz/tests/AMaybe2Tests.scala, tests/src/main/scala/scalaz/tests/AMaybeTests.scala, tests/src/main/scala/scalaz/tests/TestMain.scala
Depends on #1963.
Also rephrases the `Maybe2` docs, and adds some extra instances.
=> AMaybe tests

tests/src/main/scala/scalaz/tests/ConstTests.scala, tests/src/main/scala/scalaz/tests/TestMain.scala
Related to #1959 
As the title says, it is mostly copypasta from IListTests, and thus may be lacking in checking crucial Const-specific properties. Please point this out if it is the case.
=> Tests for Const (mostly copypasta from IListTests)

concurrent/src/main/scala/scalaz/concurrent/Future.scala
Just swap positions of `Trampoline`/`Unit` in `ContT`.
=> Fix compilation error from #1368

base/shared/src/main/scala/scalaz/data/kleisli.scala
=> Dimap and lift as methods on Kleisli

core/src/main/scala/scalaz/syntax/Syntax.scala
Updates all syntax to include ProChoice
Closes #1255
=> Adding prochoice to all syntax

README.md
=> Update site link to real URL

base/shared/src/main/scala/scalaz/tc/eq.scala
=> Remove Eq.never

build.sbt
=> zio: 0.2.7 -> 0.2.9

.travis.yml, project/ScalazBuild.scala
Mixins: https://github.com/scalaz/scalaz-plugin/blob/master/doc/TypeclassMixins.md (currently under an opt-in flag)
Made ResolutionFix a lot less brittle.
=> Scalaz plugin 0.0.6 -> 0.0.7

core/src/main/scala/scalaz/ApplicativeError.scala, core/src/main/scala/scalaz/MonadError.scala, core/src/main/scala/scalaz/Validation.scala, core/src/main/scala/scalaz/syntax/ApplicativeErrorSyntax.scala, core/src/main/scala/scalaz/syntax/MonadErrorSyntax.scala, core/src/main/scala/scalaz/syntax/Syntax.scala, example/src/main/scala/scalaz/example/SyntaxUsage.scala, project/GenTypeClass.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazProperties.scala, tests/src/test/scala/scalaz/DisjunctionTest.scala, tests/src/test/scala/scalaz/ValidationTest.scala
A very minimal implementation just by seperating out stuff from `MonadError` 
if there are sensible functions to put on `ApplicativeError` let me know!
=> ApplicativeError

core/src/main/scala/scalaz/Validation.scala, tests/src/test/scala/scalaz/ValidationTest.scala
=> Plus for Validation accumulates errors

core/src/main/scala/scalaz/Either.scala, core/src/main/scala/scalaz/EitherT.scala, tests/src/test/scala/scalaz/EitherTTest.scala
=> Add EitherT fromOption

core/src/main/scala/scalaz/Applicative.scala, core/src/main/scala/scalaz/syntax/ApplicativeSyntax.scala, tests/src/test/scala/scalaz/ApplicativeTest.scala
PR for issue #1984, with help from @jdegoes
=> plusA on Applicative (#1984)

base/shared/src/main/scala/scalaz/data/ilist.scala, base/shared/src/main/scala/scalaz/tc/apply.scala, base/shared/src/main/scala/scalaz/tc/foldable.scala, base/shared/src/test/scala/SyntaxResolutionTest.scala
Closes #1951.
@hrhino Where should I add the tests? Also, what should I do with the `FoldableSyntax` (since its using macro)?
=> Add traverse_ and sequence_

base/shared/src/main/scala/scalaz/basehierarchy.scala, base/shared/src/main/scala/scalaz/prelude.scala, base/shared/src/main/scala/scalaz/tc/applicativeplus.scala, base/shared/src/main/scala/scalaz/tc/monadplus.scala, base/shared/src/main/scala/scalaz/tc/package.scala, base/shared/src/main/scala/scalaz/tc/plus.scala, base/shared/src/main/scala/scalaz/tc/plusempty.scala, laws/shared/src/main/scala/scalaz/laws/TypeclassLaws.scala
Needed for https://github.com/scalaz/scalaz/issues/1940
=> Port minimal *Plus and PlusEmpty to 8.0.x

base/shared/src/main/scala/scalaz/tc/joinsemilattice.scala, base/shared/src/main/scala/scalaz/tc/meetsemilattice.scala
=> Fix compilation error from last merge

core/src/main/scala/scalaz/Contravariant.scala, core/src/main/scala/scalaz/std/Function.scala
fix https://github.com/scalaz/scalaz/issues/2044
=> add Contravariant#narrow

core/src/main/scala/scalaz/FingerTree.scala
We just have to accept that an empty tree has no measure (as in `Maybe.Empty` instead of `Monoid.zero`).
=> FingerTree does not need a Monoid on node summaries, Semigroup is sufficient.

core/src/main/scala/scalaz/FingerTree.scala
=> Fix documentation of FingerTree#split.

core/src/main/scala/scalaz/DList.scala, core/src/main/scala/scalaz/Dequeue.scala, core/src/main/scala/scalaz/Map.scala, core/src/main/scala/scalaz/NonEmptyList.scala, core/src/main/scala/scalaz/Tree.scala, example/src/main/scala/scalaz/example/AdjunctUsage.scala, example/src/main/scala/scalaz/example/BifunctorUsage.scala, example/src/main/scala/scalaz/example/EndoUsage.scala, example/src/main/scala/scalaz/example/Foldable1Usage.scala, example/src/main/scala/scalaz/example/TagUsage.scala
https://github.com/scala/scala/commit/9e264483d04f48513f3a82e91365667f01a2f5f3
=> avoid deprecated unicode allow chars

core/src/main/scala/scalaz/IList.scala, core/src/main/scala/scalaz/ListT.scala, core/src/main/scala/scalaz/NonEmptyList.scala, core/src/main/scala/scalaz/Zipper.scala, core/src/main/scala/scalaz/std/List.scala, core/src/main/scala/scalaz/std/Stream.scala, core/src/main/scala/scalaz/std/String.scala, core/src/main/scala/scalaz/std/Vector.scala, core/src/main/scala/scalaz/syntax/std/ListOps.scala, core/src/main/scala/scalaz/syntax/std/StreamOps.scala, core/src/main/scala/scalaz/syntax/std/StringOps.scala, core/src/main/scala/scalaz/syntax/std/VectorOps.scala, example/src/main/scala/scalaz/example/IListUsage.scala, example/src/main/scala/scalaz/example/MixedBag.scala, example/src/main/scala/scalaz/example/StringUsage.scala, tests/src/test/scala/scalaz/FoldableTest.scala, tests/src/test/scala/scalaz/IListTest.scala, tests/src/test/scala/scalaz/ListTTest.scala, tests/src/test/scala/scalaz/NonEmptyListTest.scala, tests/src/test/scala/scalaz/ZipperTest.scala, tests/src/test/scala/scalaz/std/VectorTest.scala
I left out `Option` in `List` since they both are part of standard scala collections. #2051
=> consistent IList, ListT and Zipper

core/src/main/scala/scalaz/Foldable.scala, tests/src/test/scala/scalaz/FoldableTest.scala
Fix build after merging two PRs, each of which passed the build, but combined together failed compilation.
=> Fix build after merging two PRs

core/src/main/scala/scalaz/IList.scala, tests/src/test/scala/scalaz/IListTest.scala
=> Add IList#prepend.

core/src/main/scala/scalaz/EphemeralStream.scala, core/src/main/scala/scalaz/Heap.scala, core/src/main/scala/scalaz/StrictTree.scala, core/src/main/scala/scalaz/Tree.scala, core/src/main/scala/scalaz/TreeLoc.scala, core/src/main/scala/scalaz/std/Stream.scala, core/src/main/scala/scalaz/syntax/TreeOps.scala, scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala, tests/jvm/src/test/scala/scalaz/TreeTestJVM.scala, tests/src/test/scala/scalaz/CofreeTest.scala, tests/src/test/scala/scalaz/EphemeralStreamTest.scala, tests/src/test/scala/scalaz/Eq1.scala, tests/src/test/scala/scalaz/StrictTreeTest.scala, tests/src/test/scala/scalaz/TreeLocTest.scala, tests/src/test/scala/scalaz/TreeTest.scala
@tonymorris few days back in IRC
> [dibblego: the rose tree needs to use EphemeralStream, nobody has fixed it](https://matrix.to/#/!NptldwTHyezSjqjUIi:matrix.org/$15605176762007949bSHny:matrix.org?via=matrix.org)
Here's my attempt to do the same.
=> Making Tree to use EphemeralStream from Stream

core/src/main/scala/scalaz/SelectT.scala, core/src/main/scala/scalaz/package.scala, tests/src/test/scala/scalaz/SelectTTest.scala
- https://www.cs.bham.ac.uk/~mhe/papers/selection-escardo-oliva.pdf
- https://arxiv.org/pdf/1406.2058.pdf
- https://github.com/ghc/packages-transformers/blob/0_5_4_0/Control/Monad/Trans/Select.hs
=> add SelectT

core/src/main/scala/scalaz/Either.scala, core/src/main/scala/scalaz/Validation.scala
(cherry picked from commit 5d3446e7521332b88763be61c61a1a9e8d5a3bc4)
=> add some methods in \/ and Validation

README.md
Changed to use SVG gitter badge
=> SVG gitter badge

tests/src/test/scala/scalaz/BitraverseTest.scala, tests/src/test/scala/scalaz/BooleanSyntaxTest.scala, tests/src/test/scala/scalaz/BooleanTest.scala, tests/src/test/scala/scalaz/ConstTest.scala
https://github.com/typelevel/scalacheck/blob/6f01c6a4365ca5298daa97ff52e7f4f3d38dc813/src/main/scala/org/scalacheck/Properties.scala#L107
(cherry picked from commit c01c7b81c64c0acfc15c87cd2f93c71b842ffb43)
=> prepare scalacheck 1.15.x

build.sbt, project/build.properties, project/build.scala, version.sbt
https://github.com/sbt/sbt/commit/e6fec6b1db5f212a74bf5e3766b9b70f2d983f24
https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
=> [7.2.x] sbt 1.5.2. use slash syntax

core/src/main/scala/scalaz/StreamT.scala
This PR implements the [ReactiveX distinctUntilChanged operator](http://reactivex.io/documentation/operators/distinct.html)
=> Add StreamT.distinctUntilChanged (fix #2223)

core/src/main/scala/scalaz/StreamT.scala, tests/src/test/scala/scalaz/StreamTTest.scala
This instance could provide the functionality similar to the [ReactiveX Merge operator](http://reactivex.io/documentation/operators/merge.html)
=> Add the StreamTMergeMonoid instance (for #2223)

core/src/main/scala/scalaz/StreamT.scala
This PR adds the ReactiveX `FlatMapLatest` operator into `StreamT`.
This operator would be useful to implement data-binding.
=> Add StreamT.flatMapLatest (for #2223)

core/src/main/scala/scalaz/StreamT.scala
Just a convenient utility, similar to `scala.collection.Seq.collect`
=> Add StreamT.collect

core/src/main/scala/scalaz/StreamT.scala
=> Add StreamT.scan and StreamT.scanLeft

core/src/main/scala/scalaz/StreamT.scala
`postScanLeft` takes the name from `postscan` in Haskell
https://www.stackage.org/haddock/lts-19.0/foldl-1.4.12/Control-Foldl.html#v:postscan
=> Rename scanLeftTail to postScanLeft

core/src/main/scala/scalaz/StreamT.scala, tests/jvm/src/test/scala/scalaz/StreamTTestJVM.scala
See https://reactivex.io/documentation/operators/switch.html
=> Add StreamT.switch

core/src/main/scala/scalaz/StreamT.scala, effect/src/main/scala/scalaz/effect/LiftIO.scala, tests/src/test/scala/scalaz/StreamTTest.scala
This PR would reduce the size of byte code
=> Make StreamT a SAM type

core/src/main/scala/scalaz/Align.scala, core/src/main/scala/scalaz/Applicative.scala, core/src/main/scala/scalaz/Apply.scala, core/src/main/scala/scalaz/Bind.scala, core/src/main/scala/scalaz/BindRec.scala, core/src/main/scala/scalaz/Cobind.scala, core/src/main/scala/scalaz/Comonad.scala, core/src/main/scala/scalaz/Cozip.scala, core/src/main/scala/scalaz/Distributive.scala, core/src/main/scala/scalaz/Foldable.scala, core/src/main/scala/scalaz/Foldable1.scala, core/src/main/scala/scalaz/Functor.scala, core/src/main/scala/scalaz/Monad.scala, core/src/main/scala/scalaz/Optional.scala, core/src/main/scala/scalaz/Traverse.scala, core/src/main/scala/scalaz/Traverse1.scala, core/src/main/scala/scalaz/UnwriterT.scala, core/src/main/scala/scalaz/Unzip.scala, core/src/main/scala/scalaz/WriterT.scala, core/src/main/scala/scalaz/Zip.scala, core/src/main/scala/scalaz/package.scala
for compatibility with Scala 3
=> avoid implicit in package object

core/src/main/scala/scalaz/Align.scala, core/src/main/scala/scalaz/Applicative.scala, core/src/main/scala/scalaz/Apply.scala, core/src/main/scala/scalaz/Bind.scala, core/src/main/scala/scalaz/BindRec.scala, core/src/main/scala/scalaz/Cobind.scala, core/src/main/scala/scalaz/Comonad.scala, core/src/main/scala/scalaz/Cozip.scala, core/src/main/scala/scalaz/Distributive.scala, core/src/main/scala/scalaz/Foldable.scala, core/src/main/scala/scalaz/Foldable1.scala, core/src/main/scala/scalaz/Functor.scala, core/src/main/scala/scalaz/InvariantApplicative.scala, core/src/main/scala/scalaz/Monad.scala, core/src/main/scala/scalaz/Optional.scala, core/src/main/scala/scalaz/Traverse.scala, core/src/main/scala/scalaz/Traverse1.scala, core/src/main/scala/scalaz/Unzip.scala, core/src/main/scala/scalaz/WriterT.scala, core/src/main/scala/scalaz/Zip.scala, core/src/main/scala/scalaz/package.scala, example/src/main/scala/scalaz/example/WordCount.scala
for compatibility with Scala 3
=> remove implicit Id instance in package object

core/src/main/scala/scalaz/FreeAp.scala, tests/src/test/scala/scalaz/FreeApTest.scala
https://github.com/ekmett/free/commit/1f265b79ce554458fe436d2124b283433f46db9b
=> add Foldable and Foldable1 instance for FreeAp

core/src/main/scala/scalaz/FreeAp.scala, tests/src/test/scala/scalaz/FreeApTest.scala
https://github.com/ekmett/free/blob/1f265b79ce554458fe436d2124b283433f46db9b/src/Control/Applicative/Free.hs#L98-L102
=> add Cobind and Comonad instance for FreeAp

core/src/main/scala/scalaz/ContravariantCoyoneda.scala, core/src/main/scala/scalaz/Coyoneda.scala, core/src/main/scala/scalaz/EphemeralStream.scala, core/src/main/scala/scalaz/FingerTree.scala, core/src/main/scala/scalaz/ImmutableArray.scala, core/src/main/scala/scalaz/Liskov.scala, core/src/main/scala/scalaz/MaybeT.scala, core/src/main/scala/scalaz/MonadListen.scala, core/src/main/scala/scalaz/OptionT.scala, core/src/main/scala/scalaz/Ordering.scala, core/src/main/scala/scalaz/Unapply.scala, effect/src/main/scala/scalaz/effect/MonadCatchIO.scala, effect/src/main/scala/scalaz/effect/MonadIO.scala, example/src/main/scala/scalaz/example/IsomorphismUsage.scala, iteratee/src/main/scala/scalaz/iteratee/EnumeratorT.scala, iteratee/src/main/scala/scalaz/iteratee/IterateeT.scala
=> add explicit type

core/src/main/scala/scalaz/EitherT.scala, core/src/main/scala/scalaz/Kleisli.scala, core/src/main/scala/scalaz/LazyEitherT.scala, core/src/main/scala/scalaz/OptionT.scala, core/src/main/scala/scalaz/UnwriterT.scala, core/src/main/scala/scalaz/WriterT.scala, core/src/main/scala/scalaz/std/Either.scala, core/src/main/scala/scalaz/std/Tuple.scala
- remove unnecessary `implicit`
- add `override`
=> fix warnings
